import type { Locale } from "./i18n";

type LocalizedText = Partial<Record<Locale, string>>;

export const BESPOKE_TEXT: Record<string, LocalizedText> = {
  heroEyebrow: {
    de: "Bespoke",
    en: "Bespoke",
    tr: "Bespoke",
    sk: "Bespoke",
    cs: "Bespoke",
    hu: "Bespoke",
    pl: "Bespoke",
  },
  heroTitle: {
    de: "Ein Schmuckstück, das nur für Sie gemacht wird",
    en: "A Piece Made for No One Else",
    tr: "Sadece Size Özel Bir Parça",
    sk: "Šperk, ktorý nevznikne pre nikoho iného",
    cs: "Šperk, který nevznikne pro nikoho jiného",
    hu: "Egy darab, amit senki másnak nem készítenek",
    pl: "Element stworzony wyłącznie dla Ciebie",
  },
  heroLead: {
    de: "Bei einer Bespoke-Bestellung entwerfen und fertigen wir Ihr Schmuckstück von Grund auf, ganz nach Ihren Wünschen — von der ersten Skizze bis zum letzten Polierschritt, alles in unserem eigenen Atelier.",
    en: "With a bespoke commission, we design and craft your piece from nothing, built entirely around what you have in mind — from the first sketch to the final polish, all in our own workshop.",
    tr: "Bespoke bir sipariş ile, parçanızı sıfırdan, tamamen sizin hayalinizdeki gibi tasarlıyor ve üretiyoruz — ilk eskizden son parlatmaya kadar, hepsi kendi atölyemizde.",
    sk: "Pri bespoke zákazke navrhneme a vyrobíme váš šperk úplne od základu, presne podľa vašej predstavy — od prvého náčrtu až po finálne leštenie, všetko priamo v našej dielni.",
    cs: "Při bespoke zakázce navrhneme a vyrobíme váš šperk úplně od základu, přesně podle vaší představy — od prvního náčrtu až po finální leštění, vše přímo v naší dílně.",
    hu: "Bespoke megbízás esetén a semmiből tervezzük és készítjük el az Ön darabját, teljesen az Ön elképzelése alapján — az első vázlattól az utolsó polírozásig, mindezt saját műhelyünkben.",
    pl: "W przypadku zamówienia bespoke projektujemy i wykonujemy Twój element od podstaw, w pełni zgodnie z Twoją wizją — od pierwszego szkicu po ostatnie polerowanie, wszystko w naszym własnym warsztacie.",
  },

  phase1Eyebrow: {
    de: "Phase 1",
    en: "Phase One",
    tr: "Birinci Aşama",
    sk: "Fáza 1",
    cs: "Fáze 1",
    hu: "Első szakasz",
    pl: "Etap pierwszy",
  },
  phase1Title: {
    de: "Beratung & Design",
    en: "Consultation & Design",
    tr: "Danışmanlık ve Tasarım",
    sk: "Konzultácia a dizajn",
    cs: "Konzultace a design",
    hu: "Konzultáció és tervezés",
    pl: "Konsultacja i projekt",
  },

  phase2Eyebrow: {
    de: "Phase 2",
    en: "Phase Two",
    tr: "İkinci Aşama",
    sk: "Fáza 2",
    cs: "Fáze 2",
    hu: "Második szakasz",
    pl: "Etap drugi",
  },
  phase2Title: {
    de: "Handwerk",
    en: "Craftsmanship",
    tr: "Ustalık",
    sk: "Remeselná výroba",
    cs: "Řemeslná výroba",
    hu: "Kézművesség",
    pl: "Rzemiosło",
  },

  phase3Eyebrow: {
    de: "Phase 3",
    en: "Phase Three",
    tr: "Üçüncü Aşama",
    sk: "Fáza 3",
    cs: "Fáze 3",
    hu: "Harmadik szakasz",
    pl: "Etap trzeci",
  },
  phase3Title: {
    de: "Veredelung & Übergabe",
    en: "Finishing & Delivery",
    tr: "Bitirme ve Teslimat",
    sk: "Dokončenie a odovzdanie",
    cs: "Dokončení a předání",
    hu: "Befejezés és átadás",
    pl: "Wykończenie i wydanie",
  },

  ctaTitle: {
    de: "Beginnen Sie Ihr Bespoke-Projekt",
    en: "Start Your Bespoke Piece",
    tr: "Bespoke Parçanızı Başlatın",
    sk: "Začnite svoj bespoke šperk",
    cs: "Začněte svůj bespoke šperk",
    hu: "Kezdje el bespoke darabját",
    pl: "Rozpocznij swój projekt bespoke",
  },
  ctaSub: {
    de: "Vereinbaren Sie einen privaten Termin in einer unserer Boutiquen und besprechen Sie Ihre Idee mit unserem Designteam.",
    en: "Book a private appointment at one of our boutiques and talk through your idea with our design team.",
    tr: "Butiklerimizden birinde özel bir randevu alın ve fikrinizi tasarım ekibimizle konuşun.",
    sk: "Dohodnite si súkromné stretnutie v niektorom z našich butikov a preberte svoj nápad s naším dizajnérskym tímom.",
    cs: "Domluvte si soukromou schůzku v některém z našich butiků a proberte svůj nápad s naším designérským týmem.",
    hu: "Foglaljon privát időpontot valamelyik butikunkban, és beszélje meg elképzelését tervező csapatunkkal.",
    pl: "Umów się na prywatne spotkanie w jednym z naszych butików i omów swój pomysł z naszym zespołem projektowym.",
  },
};

export type BespokeStep = {
  image: string;
  imageAlt: string;
  title: LocalizedText;
  description: LocalizedText;
};

export const PHASE_1_STEPS: BespokeStep[] = [
  {
    image: "/images/bespoke/step-01.jpg",
    imageAlt: "Client discussing their jewellery design with our designer",
    title: {
      de: "Beratung",
      en: "Consultation",
      tr: "Danışmanlık",
      sk: "Konzultácia",
      cs: "Konzultace",
      hu: "Konzultáció",
      pl: "Konsultacja",
    },
    description: {
      de: "Wir beginnen mit einem Gespräch — Ihre Ideen, der Anlass, und was das Stück für Sie bedeuten soll.",
      en: "We begin with a conversation — your ideas, the occasion, and what the piece should mean to you.",
      tr: "Bir sohbetle başlıyoruz — fikirleriniz, özel gün ve parçanın sizin için ne anlama gelmesi gerektiği.",
      sk: "Začíname rozhovorom — o vašich predstavách, príležitosti a o tom, čo má šperk pre vás znamenať.",
      cs: "Začínáme rozhovorem — o vašich představách, příležitosti a o tom, co má šperk pro vás znamenat.",
      hu: "Egy beszélgetéssel kezdjük — az Ön elképzeléseivel, az alkalommal, és azzal, mit jelentsen Önnek a darab.",
      pl: "Zaczynamy od rozmowy — o Twoich pomysłach, okazji i o tym, co ten element ma dla Ciebie oznaczać.",
    },
  },
  {
    image: "/images/bespoke/step-02.jpg",
    imageAlt: "Hand-drawn pencil sketch of a ring design",
    title: {
      de: "Skizze",
      en: "Sketch",
      tr: "Eskiz",
      sk: "Náčrt",
      cs: "Náčrt",
      hu: "Vázlat",
      pl: "Szkic",
    },
    description: {
      de: "Ihre Vorstellung wird in eine handgezeichnete Skizze übersetzt und gemeinsam verfeinert, bis sie genau stimmt.",
      en: "Your vision is translated into a hand-drawn design, refined together until it feels right.",
      tr: "Vizyonunuz elle çizilmiş bir tasarıma dönüştürülür ve doğru hissettirene kadar birlikte geliştirilir.",
      sk: "Vašu predstavu premeníme na ručne kreslený návrh, ktorý spoločne dolaďujeme, kým nesedí presne.",
      cs: "Vaši představu proměníme v ručně kreslený návrh, který společně dolaďujeme, dokud nesedí přesně.",
      hu: "Elképzelését kézzel rajzolt tervvé alakítjuk, amelyet közösen finomítunk, amíg tökéletes nem lesz.",
      pl: "Twoja wizja zostaje przełożona na ręcznie rysowany projekt, wspólnie dopracowywany, aż będzie idealny.",
    },
  },
  {
    image: "/images/bespoke/step-03.jpg",
    imageAlt: "3D CAD render of a ring design on a computer screen",
    title: {
      de: "CAD-Design",
      en: "CAD Design",
      tr: "CAD Tasarımı",
      sk: "CAD dizajn",
      cs: "CAD design",
      hu: "CAD tervezés",
      pl: "Projekt CAD",
    },
    description: {
      de: "Aus der Skizze wird ein präzises 3D-Digitalmodell, damit Sie jedes Detail sehen können, bevor es gefertigt wird.",
      en: "The sketch becomes a precise 3D digital model, so you can see every detail before it's made.",
      tr: "Eskiz, hassas bir 3D dijital modele dönüşür, böylece üretilmeden önce her detayı görebilirsiniz.",
      sk: "Náčrt sa premení na presný 3D digitálny model, aby ste videli každý detail ešte pred samotnou výrobou.",
      cs: "Náčrt se promění v přesný 3D digitální model, abyste viděli každý detail ještě před samotnou výrobou.",
      hu: "A vázlatból precíz 3D digitális modell készül, hogy minden részletet láthasson, mielőtt elkészülne a darab.",
      pl: "Szkic zamienia się w precyzyjny model 3D, dzięki czemu widzisz każdy szczegół, zanim element powstanie.",
    },
  },
];

export const PHASE_2_STEPS: BespokeStep[] = [
  {
    image: "/images/bespoke/step-04.jpg",
    imageAlt: "Jeweller engraving a green wax ring model",
    title: {
      de: "Wachsmodell",
      en: "Wax Model",
      tr: "Balmumu Model",
      sk: "Voskový model",
      cs: "Voskový model",
      hu: "Viaszmodell",
      pl: "Model woskowy",
    },
    description: {
      de: "Aus dem Design wird ein Wachsmodell geschnitzt — exakt die Form, die das Metall später annehmen wird.",
      en: "A wax model is carved from the design — the exact shape the metal will take.",
      tr: "Tasarımdan bir balmumu model oyulur — metalin alacağı tam şekil budur.",
      sk: "Podľa dizajnu vyrezávame voskový model — presný tvar, ktorý neskôr dostane kov.",
      cs: "Podle designu vyřezáváme voskový model — přesný tvar, který později dostane kov.",
      hu: "A tervből viaszmodellt faragunk — pontosan azt a formát, amelyet a fém felvesz majd.",
      pl: "Na podstawie projektu rzeźbimy model woskowy — dokładny kształt, jaki przyjmie metal.",
    },
  },
  {
    image: "/images/bespoke/step-05.jpg",
    imageAlt: "Molten metal being poured during the casting process",
    title: {
      de: "Guss",
      en: "Casting",
      tr: "Döküm",
      sk: "Odlievanie",
      cs: "Odlévání",
      hu: "Öntés",
      pl: "Odlewanie",
    },
    description: {
      de: "Das Metall wird geschmolzen und von Hand aus dem Wachsmodell in unserer Werkstatt gegossen.",
      en: "The metal is cast from the wax model, molten and poured by hand in our workshop.",
      tr: "Metal, balmumu modelden dökülür — atölyemizde elle eritilip dökülür.",
      sk: "Kov sa odleje podľa voskového modelu — v našej dielni ho ručne roztavíme a odlejeme.",
      cs: "Kov se odlije podle voskového modelu — v naší dílně ho ručně roztavíme a odlijeme.",
      hu: "A fémet a viaszmodell alapján öntjük — műhelyünkben kézzel olvasztjuk és öntjük.",
      pl: "Metal jest odlewany na podstawie modelu woskowego — topiony i odlewany ręcznie w naszym warsztacie.",
    },
  },
  {
    image: "/images/bespoke/step-06.jpg",
    imageAlt: "Jeweller shaping the prongs of a ring to hold a stone",
    title: {
      de: "Fassung vorbereiten",
      en: "Shaping the Setting",
      tr: "Yuvayı Şekillendirme",
      sk: "Príprava objímky",
      cs: "Příprava objímky",
      hu: "A foglalat kialakítása",
      pl: "Kształtowanie oprawy",
    },
    description: {
      de: "Die Krappen werden geformt und angepasst, damit sie Ihren Stein sicher und schön halten.",
      en: "Prongs are shaped and fitted, built to hold your stone securely and beautifully.",
      tr: "Pençeler şekillendirilir ve yerleştirilir — taşınızı güvenli ve zarif bir şekilde tutacak şekilde.",
      sk: "Kotlíky sa tvarujú a upravujú tak, aby váš kameň bezpečne a krásne držali.",
      cs: "Kotlíky se tvarují a upravují tak, aby váš kámen bezpečně a krásně držely.",
      hu: "A karmokat úgy alakítjuk és illesztjük, hogy biztonságosan és szépen tartsák a követ.",
      pl: "Ząbki są kształtowane i dopasowywane tak, by bezpiecznie i pięknie utrzymać Twój kamień.",
    },
  },
  {
    image: "/images/bespoke/step-07.jpg",
    imageAlt: "Jeweller carefully setting a diamond into a ring with tweezers",
    title: {
      de: "Stein fassen",
      en: "Setting the Stone",
      tr: "Taşı Yerleştirme",
      sk: "Osadenie kameňa",
      cs: "Osazení kamene",
      hu: "A kő befoglalása",
      pl: "Osadzanie kamienia",
    },
    description: {
      de: "Der Stein wird von Hand gefasst, geprüft und justiert, bis er perfekt sitzt.",
      en: "The stone is set by hand, checked and adjusted until it sits perfectly.",
      tr: "Taş elle yerleştirilir, mükemmel oturana kadar kontrol edilir ve ayarlanır.",
      sk: "Kameň sa osadzuje ručne, kontroluje a dolaďuje, kým nesedí dokonale.",
      cs: "Kámen se osazuje ručně, kontroluje a dolaďuje, dokud nesedí dokonale.",
      hu: "A követ kézzel foglalják be, ellenőrzik és igazítják, amíg tökéletesen nem illeszkedik.",
      pl: "Kamień jest osadzany ręcznie, sprawdzany i regulowany, aż idealnie się ułoży.",
    },
  },
  {
    image: "/images/bespoke/step-08.jpg",
    imageAlt: "Ring being polished on a polishing wheel",
    title: {
      de: "Polieren",
      en: "Polishing",
      tr: "Parlatma",
      sk: "Leštenie",
      cs: "Leštění",
      hu: "Polírozás",
      pl: "Polerowanie",
    },
    description: {
      de: "Das Stück wird auf Hochglanz poliert, um seine volle Brillanz zu entfalten.",
      en: "The piece is polished to a mirror finish, bringing out its full brilliance.",
      tr: "Parça, tüm parlaklığını ortaya çıkaracak şekilde ayna gibi parlatılır.",
      sk: "Šperk sa vyleští do zrkadlového lesku, aby vynikla jeho plná brilancia.",
      cs: "Šperk se vyleští do zrcadlového lesku, aby vynikla jeho plná brilance.",
      hu: "A darabot tükörfényesre polírozzuk, hogy teljes ragyogása kibontakozzon.",
      pl: "Element jest polerowany na wysoki połysk, aby uwydatnić jego pełny blask.",
    },
  },
];

export const PHASE_3_STEPS: BespokeStep[] = [
  {
    image: "/images/bespoke/step-09.jpg",
    imageAlt: "Jeweller inspecting a finished ring with a loupe, wearing white gloves",
    title: {
      de: "Qualitätsprüfung",
      en: "Quality Inspection",
      tr: "Kalite Kontrolü",
      sk: "Kontrola kvality",
      cs: "Kontrola kvality",
      hu: "Minőségellenőrzés",
      pl: "Kontrola jakości",
    },
    description: {
      de: "Jedes Detail wird unter Vergrößerung geprüft — nichts verlässt unsere Werkstatt ungeprüft.",
      en: "Every detail is checked under magnification — nothing leaves our workshop unchecked.",
      tr: "Her detay büyüteç altında kontrol edilir — hiçbir şey atölyemizden kontrolsüz çıkmaz.",
      sk: "Každý detail kontrolujeme pod zväčšením — z našej dielne neodíde nič neskontrolované.",
      cs: "Každý detail kontrolujeme pod zvětšením — z naší dílny neodejde nic nezkontrolované.",
      hu: "Minden részletet nagyítás alatt ellenőrzünk — semmi nem hagyja el a műhelyünket ellenőrzés nélkül.",
      pl: "Każdy detal sprawdzamy pod powiększeniem — nic nie opuszcza naszego warsztatu bez kontroli.",
    },
  },
  {
    image: "/images/bespoke/step-10.jpg",
    imageAlt: "Jeweller applying final finishing touches to a ring",
    title: {
      de: "Letzter Schliff",
      en: "Final Finishing",
      tr: "Son Rötuşlar",
      sk: "Finálne dokončenie",
      cs: "Finální dokončení",
      hu: "Végső simítások",
      pl: "Ostatnie poprawki",
    },
    description: {
      de: "Letzte Handgriffe und Anpassungen, damit sich das Stück genau richtig anfühlt.",
      en: "Final touches and adjustments, so the piece feels exactly right.",
      tr: "Parçanın tam olarak doğru hissettirmesi için son dokunuşlar ve ayarlamalar yapılır.",
      sk: "Posledné úpravy a doladenia, aby šperk sedel presne tak, ako má.",
      cs: "Poslední úpravy a doladění, aby šperk seděl přesně tak, jak má.",
      hu: "Utolsó igazítások és finomítások, hogy a darab pontosan úgy érződjön, ahogy kell.",
      pl: "Ostatnie poprawki i regulacje, aby element czuł się dokładnie tak, jak powinien.",
    },
  },
  {
    image: "/images/bespoke/step-11.jpg",
    imageAlt: "Finished ring presented in an open velvet box with ribbon",
    title: {
      de: "Präsentation",
      en: "Presentation",
      tr: "Sunum",
      sk: "Prezentácia",
      cs: "Prezentace",
      hu: "Bemutatás",
      pl: "Prezentacja",
    },
    description: {
      de: "Ihr Stück wird in seiner Box präsentiert, bereit für den Moment, für den es gemacht wurde.",
      en: "Your piece is presented in its box, ready for the moment it was made for.",
      tr: "Parçanız kutusunda sunulur — yapıldığı o an için hazır.",
      sk: "Váš šperk je uložený vo svojej krabičke, pripravený na chvíľu, pre ktorú bol stvorený.",
      cs: "Váš šperk je uložený ve své krabičce, připravený na chvíli, pro kterou byl stvořen.",
      hu: "Az Ön darabja a dobozában várja, hogy elérkezzen az a pillanat, amelyre készült.",
      pl: "Twój element prezentowany jest w pudełku, gotowy na chwilę, dla której powstał.",
    },
  },
  {
    image: "/images/bespoke/step-12.jpg",
    imageAlt: "The finished ring being handed over to the client in its box",
    title: {
      de: "Übergabe",
      en: "Delivery",
      tr: "Teslimat",
      sk: "Odovzdanie",
      cs: "Předání",
      hu: "Átadás",
      pl: "Wydanie",
    },
    description: {
      de: "Übergeben an Sie — ein Stück, das für niemand anderen gemacht wurde, genau so, wie Sie es sich vorgestellt haben.",
      en: "Delivered to you — a piece made for no one else, exactly as you imagined it.",
      tr: "Size teslim edilir — başka hiç kimse için yapılmamış, tam olarak hayal ettiğiniz gibi bir parça.",
      sk: "Odovzdaný vám — šperk, ktorý nevznikol pre nikoho iného, presne taký, aký ste si predstavovali.",
      cs: "Předaný vám — šperk, který nevznikl pro nikoho jiného, přesně takový, jaký jste si představovali.",
      hu: "Önnek átadva — egy darab, amit senki másnak nem készítettek, pontosan úgy, ahogy elképzelte.",
      pl: "Wręczony Tobie — element stworzony wyłącznie dla Ciebie, dokładnie taki, jak sobie wyobrażałeś.",
    },
  },
];
