import type { Locale } from "./i18n";

type LocalizedText = Partial<Record<Locale, string>>;

export const BESPOKE_TEXT: Record<string, LocalizedText> = {
  heroEyebrow: {
    de: "Bespoke",
    en: "Bespoke",
    tr: "Bespoke",
    sk: "Bespoke",
    cs: "Bespoke",
    hu: "Bespoke",
    pl: "Bespoke",
    ru: "На заказ",
    nl: "Maatwerk",
    da: "Skræddersyet",
    fi: "Mittatilaus",
    sv: "Skräddarsytt",
    fr: "Sur mesure",
    it: "Su misura",
    es: "A medida",
  },

  heroTitle: {
    de: "Ein Schmuckstück, das nur für Sie gemacht wird",
    en: "A Piece Made for No One Else",
    tr: "Sadece Size Özel Bir Parça",
    sk: "Šperk, ktorý nevznikne pre nikoho iného",
    cs: "Šperk, který nevznikne pro nikoho jiného",
    hu: "Egy darab, amit senki másnak nem készítenek",
    pl: "Element stworzony wyłącznie dla Ciebie",
    ru: "Украшение, созданное только для вас",
    nl: "Een sieraad dat alleen voor u wordt gemaakt",
    da: "Et smykke skabt kun til dig",
    fi: "Koru, joka tehdään vain sinulle",
    sv: "Ett smycke skapat endast för dig",
    fr: "Une pièce créée uniquement pour vous",
    it: "Un gioiello creato soltanto per voi",
    es: "Una pieza creada exclusivamente para usted",
  },

  heroLead: {
    de: "Bei einer Bespoke-Bestellung entwerfen und fertigen wir Ihr Schmuckstück von Grund auf, ganz nach Ihren Wünschen — von der ersten Skizze bis zum letzten Polierschritt, alles in unserem eigenen Atelier.",
    en: "With a bespoke commission, we design and craft your piece from nothing, built entirely around what you have in mind — from the first sketch to the final polish, all in our own workshop.",
    tr: "Bespoke bir sipariş ile, parçanızı sıfırdan, tamamen sizin hayalinizdeki gibi tasarlıyor ve üretiyoruz — ilk eskizden son parlatmaya kadar, hepsi kendi atölyemizde.",
    sk: "Pri bespoke zákazke navrhneme a vyrobíme váš šperk úplne od základu, presne podľa vašej predstavy — od prvého náčrtu až po finálne leštenie, všetko priamo v našej dielni.",
    cs: "Při bespoke zakázce navrhneme a vyrobíme váš šperk úplně od základu, přesně podle vaší představy — od prvního náčrtu až po finální leštění, vše přímo v naší dílně.",
    hu: "Bespoke megbízás esetén a semmiből tervezzük és készítjük el az Ön darabját, teljesen az Ön elképzelése alapján — az első vázlattól az utolsó polírozásig, mindezt saját műhelyünkben.",
    pl: "W przypadku zamówienia bespoke projektujemy i wykonujemy Twój element od podstaw, w pełni zgodnie z Twoją wizją — od pierwszego szkicu po ostatnie polerowanie, wszystko w naszym własnym warsztacie.",
    ru: "При индивидуальном заказе мы проектируем и создаём ваше украшение с нуля, полностью основываясь на вашей идее — от первого эскиза до финальной полировки, всё в нашей собственной мастерской.",
    nl: "Bij een maatwerkopdracht ontwerpen en vervaardigen we uw sieraad volledig vanaf nul, helemaal rond uw wensen — van de eerste schets tot de laatste polijstbeurt, alles in ons eigen atelier.",
    da: "Ved en skræddersyet bestilling designer og fremstiller vi dit smykke helt fra bunden efter dine ønsker — fra den første skitse til den sidste polering, alt i vores eget værksted.",
    fi: "Mittatilaustyössä suunnittelemme ja valmistamme korusi alusta alkaen täysin toiveidesi mukaan — ensimmäisestä luonnoksesta viimeiseen kiillotukseen, kaikki omassa verstaassamme.",
    sv: "Vid en skräddarsydd beställning designar och tillverkar vi ditt smycke helt från grunden utifrån dina önskemål — från den första skissen till den sista poleringen, allt i vår egen verkstad.",
    fr: "Pour une création sur mesure, nous concevons et réalisons votre bijou entièrement à partir de votre idée — du premier croquis au polissage final, le tout dans notre propre atelier.",
    it: "Con una creazione su misura, progettiamo e realizziamo il vostro gioiello da zero, interamente sulla base dei vostri desideri — dal primo schizzo alla lucidatura finale, tutto nel nostro laboratorio.",
    es: "Con un encargo a medida, diseñamos y elaboramos su joya desde cero, completamente en torno a su idea — desde el primer boceto hasta el pulido final, todo en nuestro propio taller.",
  },

  phase1Eyebrow: {
    de: "Phase 1",
    en: "Phase One",
    tr: "Birinci Aşama",
    sk: "Fáza 1",
    cs: "Fáze 1",
    hu: "Első szakasz",
    pl: "Etap pierwszy",
    ru: "Этап 1",
    nl: "Fase 1",
    da: "Fase 1",
    fi: "Vaihe 1",
    sv: "Fas 1",
    fr: "Phase 1",
    it: "Fase 1",
    es: "Fase 1",
  },

  phase1Title: {
    de: "Beratung & Design",
    en: "Consultation & Design",
    tr: "Danışmanlık ve Tasarım",
    sk: "Konzultácia a dizajn",
    cs: "Konzultace a design",
    hu: "Konzultáció és tervezés",
    pl: "Konsultacja i projekt",
    ru: "Консультация и дизайн",
    nl: "Consultatie & ontwerp",
    da: "Konsultation & design",
    fi: "Konsultaatio & suunnittelu",
    sv: "Konsultation & design",
    fr: "Consultation & design",
    it: "Consulenza & design",
    es: "Consulta & diseño",
  },

  phase2Eyebrow: {
    de: "Phase 2",
    en: "Phase Two",
    tr: "İkinci Aşama",
    sk: "Fáza 2",
    cs: "Fáze 2",
    hu: "Második szakasz",
    pl: "Etap drugi",
    ru: "Этап 2",
    nl: "Fase 2",
    da: "Fase 2",
    fi: "Vaihe 2",
    sv: "Fas 2",
    fr: "Phase 2",
    it: "Fase 2",
    es: "Fase 2",
  },

  phase2Title: {
    de: "Handwerk",
    en: "Craftsmanship",
    tr: "Ustalık",
    sk: "Remeselná výroba",
    cs: "Řemeslná výroba",
    hu: "Kézművesség",
    pl: "Rzemiosło",
    ru: "Мастерство",
    nl: "Vakmanschap",
    da: "Håndværk",
    fi: "Käsityötaito",
    sv: "Hantverk",
    fr: "Savoir-faire",
    it: "Artigianalità",
    es: "Artesanía",
  },

  phase3Eyebrow: {
    de: "Phase 3",
    en: "Phase Three",
    tr: "Üçüncü Aşama",
    sk: "Fáza 3",
    cs: "Fáze 3",
    hu: "Harmadik szakasz",
    pl: "Etap trzeci",
    ru: "Этап 3",
    nl: "Fase 3",
    da: "Fase 3",
    fi: "Vaihe 3",
    sv: "Fas 3",
    fr: "Phase 3",
    it: "Fase 3",
    es: "Fase 3",
  },

  phase3Title: {
    de: "Veredelung & Übergabe",
    en: "Finishing & Delivery",
    tr: "Bitirme ve Teslimat",
    sk: "Dokončenie a odovzdanie",
    cs: "Dokončení a předání",
    hu: "Befejezés és átadás",
    pl: "Wykończenie i wydanie",
    ru: "Финишная обработка и передача",
    nl: "Afwerking & oplevering",
    da: "Færdiggørelse & levering",
    fi: "Viimeistely & luovutus",
    sv: "Slutfinish & leverans",
    fr: "Finition & remise",
    it: "Finitura & consegna",
    es: "Acabado & entrega",
  },

  ctaTitle: {
    de: "Beginnen Sie Ihr Bespoke-Projekt",
    en: "Start Your Bespoke Piece",
    tr: "Bespoke Parçanızı Başlatın",
    sk: "Začnite svoj bespoke šperk",
    cs: "Začněte svůj bespoke šperk",
    hu: "Kezdje el bespoke darabját",
    pl: "Rozpocznij swój projekt bespoke",
    ru: "Начните создание вашего украшения",
    nl: "Begin met uw maatwerksieraad",
    da: "Start dit skræddersyede smykke",
    fi: "Aloita mittatilauskorusi",
    sv: "Börja skapa ditt skräddarsydda smycke",
    fr: "Commencez votre création sur mesure",
    it: "Iniziate il vostro gioiello su misura",
    es: "Comience su joya a medida",
  },

  ctaSub: {
    de: "Vereinbaren Sie einen privaten Termin in einer unserer Boutiquen und besprechen Sie Ihre Idee mit unserem Designteam.",
    en: "Book a private appointment at one of our boutiques and talk through your idea with our design team.",
    tr: "Butiklerimizden birinde özel bir randevu alın ve fikrinizi tasarım ekibimizle konuşun.",
    sk: "Dohodnite si súkromné stretnutie v niektorom z našich butikov a preberte svoj nápad s naším dizajnérskym tímom.",
    cs: "Domluvte si soukromou schůzku v některém z našich butiků a proberte svůj nápad s naším designérským týmem.",
    hu: "Foglaljon privát időpontot valamelyik butikunkban, és beszélje meg elképzelését tervező csapatunkkal.",
    pl: "Umów się na prywatne spotkanie w jednym z naszych butików i omów swój pomysł z naszym zespołem projektowym.",
    ru: "Запишитесь на индивидуальную встречу в одном из наших бутиков и обсудите свою идею с нашей командой дизайнеров.",
    nl: "Boek een privéafspraak in een van onze boetieks en bespreek uw idee met ons ontwerpteam.",
    da: "Book en privat aftale i en af vores boutiques og drøft din idé med vores designteam.",
    fi: "Varaa yksityinen tapaaminen yhdessä myymälöistämme ja keskustele ideastasi suunnittelutiimimme kanssa.",
    sv: "Boka ett privat möte i en av våra butiker och diskutera din idé med vårt designteam.",
    fr: "Prenez rendez-vous dans l’une de nos boutiques et échangez sur votre idée avec notre équipe de design.",
    it: "Prenotate un appuntamento privato in una delle nostre boutique e discutete la vostra idea con il nostro team di design.",
    es: "Reserve una cita privada en una de nuestras boutiques y comente su idea con nuestro equipo de diseño.",
  },
};

export type BespokeStep = {
  image: string;
  imageAlt: string;
  title: LocalizedText;
  description: LocalizedText;
};

export const PHASE_1_STEPS: BespokeStep[] = [
  {
    image: "/images/bespoke/step-01.jpg",
    imageAlt:
      "Client discussing their jewellery design with our designer",
    title: {
      de: "Beratung",
      en: "Consultation",
      tr: "Danışmanlık",
      sk: "Konzultácia",
      cs: "Konzultace",
      hu: "Konzultáció",
      pl: "Konsultacja",
      ru: "Консультация",
      nl: "Consultatie",
      da: "Konsultation",
      fi: "Konsultaatio",
      sv: "Konsultation",
      fr: "Consultation",
      it: "Consulenza",
      es: "Consulta",
    },
    description: {
      de: "Wir beginnen mit einem Gespräch — Ihre Ideen, der Anlass, und was das Stück für Sie bedeuten soll.",
      en: "We begin with a conversation — your ideas, the occasion, and what the piece should mean to you.",
      tr: "Bir sohbetle başlıyoruz — fikirleriniz, özel gün ve parçanın sizin için ne anlama gelmesi gerektiği.",
      sk: "Začíname rozhovorom — o vašich predstavách, príležitosti a o tom, čo má šperk pre vás znamenať.",
      cs: "Začínáme rozhovorem — o vašich představách, příležitosti a o tom, co má šperk pro vás znamenat.",
      hu: "Egy beszélgetéssel kezdjük — az Ön elképzeléseivel, az alkalommal, és azzal, mit jelentsen Önnek a darab.",
      pl: "Zaczynamy od rozmowy — o Twoich pomysłach, okazji i o tym, co ten element ma dla Ciebie oznaczać.",
      ru: "Мы начинаем с разговора — о ваших идеях, поводе и о том, какое значение должно иметь для вас украшение.",
      nl: "We beginnen met een gesprek — over uw ideeën, de gelegenheid en wat het sieraad voor u moet betekenen.",
      da: "Vi begynder med en samtale — om dine idéer, anledningen og hvad smykket skal betyde for dig.",
      fi: "Aloitamme keskustelulla — ideoistasi, tilaisuudesta ja siitä, mitä korun tulisi merkitä sinulle.",
      sv: "Vi börjar med ett samtal — om dina idéer, tillfället och vad smycket ska betyda för dig.",
      fr: "Nous commençons par une conversation — vos idées, l’occasion et ce que le bijou doit représenter pour vous.",
      it: "Iniziamo con una conversazione — le vostre idee, l’occasione e ciò che il gioiello deve rappresentare per voi.",
      es: "Comenzamos con una conversación — sus ideas, la ocasión y lo que la pieza debe significar para usted.",
    },
  },

  {
    image: "/images/bespoke/step-02.jpg",
    imageAlt: "Hand-drawn pencil sketch of a ring design",
    title: {
      de: "Skizze",
      en: "Sketch",
      tr: "Eskiz",
      sk: "Náčrt",
      cs: "Náčrt",
      hu: "Vázlat",
      pl: "Szkic",
      ru: "Эскиз",
      nl: "Schets",
      da: "Skitse",
      fi: "Luonnos",
      sv: "Skiss",
      fr: "Croquis",
      it: "Schizzo",
      es: "Boceto",
    },
    description: {
      de: "Ihre Vorstellung wird in eine handgezeichnete Skizze übersetzt und gemeinsam verfeinert, bis sie genau stimmt.",
      en: "Your vision is translated into a hand-drawn design, refined together until it feels right.",
      tr: "Vizyonunuz elle çizilmiş bir tasarıma dönüştürülür ve doğru hissettirene kadar birlikte geliştirilir.",
      sk: "Vašu predstavu premeníme na ručne kreslený návrh, ktorý spoločne dolaďujeme, kým nesedí presne.",
      cs: "Vaši představu proměníme v ručně kreslený návrh, který společně dolaďujeme, dokud nesedí přesně.",
      hu: "Elképzelését kézzel rajzolt tervvé alakítjuk, amelyet közösen finomítunk, amíg tökéletes nem lesz.",
      pl: "Twoja wizja zostaje przełożona na ręcznie rysowany projekt, wspólnie dopracowywany, aż będzie idealny.",
      ru: "Вашу идею мы превращаем в эскиз, нарисованный от руки, и вместе совершенствуем его до идеального результата.",
      nl: "Uw visie wordt vertaald naar een handgetekend ontwerp, dat we samen verfijnen tot alles precies klopt.",
      da: "Din vision omsættes til en håndtegnet skitse, som vi sammen finjusterer, indtil den føles helt rigtig.",
      fi: "Visiosi muutetaan käsin piirretyksi luonnokseksi, jota hiomme yhdessä, kunnes se tuntuu juuri oikealta.",
      sv: "Din vision omvandlas till en handritad skiss som vi tillsammans förfinar tills allt känns rätt.",
      fr: "Votre vision devient un dessin réalisé à la main, que nous affinons ensemble jusqu’à obtenir le résultat parfait.",
      it: "La vostra visione viene trasformata in un disegno a mano, perfezionato insieme fino a raggiungere il risultato desiderato.",
      es: "Su visión se convierte en un diseño dibujado a mano, que perfeccionamos juntos hasta que resulte perfecto.",
    },
  },

  {
    image: "/images/bespoke/step-03.jpg",
    imageAlt:
      "3D CAD render of a ring design on a computer screen",
    title: {
      de: "CAD-Design",
      en: "CAD Design",
      tr: "CAD Tasarımı",
      sk: "CAD dizajn",
      cs: "CAD design",
      hu: "CAD tervezés",
      pl: "Projekt CAD",
      ru: "CAD-дизайн",
      nl: "CAD-ontwerp",
      da: "CAD-design",
      fi: "CAD-suunnittelu",
      sv: "CAD-design",
      fr: "Conception CAD",
      it: "Design CAD",
      es: "Diseño CAD",
    },
    description: {
      de: "Aus der Skizze wird ein präzises 3D-Digitalmodell, damit Sie jedes Detail sehen können, bevor es gefertigt wird.",
      en: "The sketch becomes a precise 3D digital model, so you can see every detail before it's made.",
      tr: "Eskiz, hassas bir 3D dijital modele dönüşür, böylece üretilmeden önce her detayı görebilirsiniz.",
      sk: "Náčrt sa premení na presný 3D digitálny model, aby ste videli každý detail ešte pred samotnou výrobou.",
      cs: "Náčrt se promění v přesný 3D digitální model, abyste viděli každý detail ještě před samotnou výrobou.",
      hu: "A vázlatból precíz 3D digitális modell készül, hogy minden részletet láthasson, mielőtt elkészülne a darab.",
      pl: "Szkic zamienia się w precyzyjny model 3D, dzięki czemu widzisz każdy szczegół, zanim element powstanie.",
      ru: "Эскиз превращается в точную цифровую 3D-модель, чтобы вы могли увидеть каждую деталь ещё до начала изготовления.",
      nl: "De schets wordt omgezet in een nauwkeurig digitaal 3D-model, zodat u elk detail kunt bekijken voordat het sieraad wordt gemaakt.",
      da: "Skitsen bliver til en præcis digital 3D-model, så du kan se alle detaljer, før smykket fremstilles.",
      fi: "Luonnoksesta tehdään tarkka digitaalinen 3D-malli, jotta näet jokaisen yksityiskohdan ennen valmistusta.",
      sv: "Skissen blir en exakt digital 3D-modell så att du kan se varje detalj innan smycket tillverkas.",
      fr: "Le croquis devient un modèle numérique 3D précis afin que vous puissiez voir chaque détail avant la fabrication.",
      it: "Lo schizzo diventa un preciso modello digitale 3D, così potrete vedere ogni dettaglio prima della realizzazione.",
      es: "El boceto se convierte en un modelo digital 3D preciso para que pueda ver cada detalle antes de su fabricación.",
    },
  },
];

export const PHASE_2_STEPS: BespokeStep[] = [
  {
    image: "/images/bespoke/step-04.jpg",
    imageAlt: "Jeweller engraving a green wax ring model",
    title: {
      de: "Wachsmodell",
      en: "Wax Model",
      tr: "Balmumu Model",
      sk: "Voskový model",
      cs: "Voskový model",
      hu: "Viaszmodell",
      pl: "Model woskowy",
      ru: "Восковая модель",
      nl: "Wasmodel",
      da: "Voksmodel",
      fi: "Vahamalli",
      sv: "Vaxmodell",
      fr: "Modèle en cire",
      it: "Modello in cera",
      es: "Modelo de cera",
    },
    description: {
      de: "Aus dem Design wird ein Wachsmodell geschnitzt — exakt die Form, die das Metall später annehmen wird.",
      en: "A wax model is carved from the design — the exact shape the metal will take.",
      tr: "Tasarımdan bir balmumu model oyulur — metalin alacağı tam şekil budur.",
      sk: "Podľa dizajnu vyrezávame voskový model — presný tvar, ktorý neskôr dostane kov.",
      cs: "Podle designu vyřezáváme voskový model — přesný tvar, který později dostane kov.",
      hu: "A tervből viaszmodellt faragunk — pontosan azt a formát, amelyet a fém felvesz majd.",
      pl: "Na podstawie projektu rzeźbimy model woskowy — dokładny kształt, jaki przyjmie metal.",
      ru: "По дизайну создаётся восковая модель — точная форма, которую впоследствии примет металл.",
      nl: "Uit het ontwerp wordt een wasmodel vervaardigd — precies de vorm die het metaal later zal aannemen.",
      da: "Ud fra designet udskæres en voksmodel — præcis den form, metallet senere får.",
      fi: "Suunnitelman pohjalta veistetään vahamalli — täsmälleen se muoto, jonka metalli myöhemmin saa.",
      sv: "Utifrån designen skapas en vaxmodell — exakt den form som metallen senare kommer att få.",
      fr: "Un modèle en cire est sculpté à partir du design — exactement la forme que prendra ensuite le métal.",
      it: "Dal progetto viene scolpito un modello in cera — la forma esatta che il metallo assumerà.",
      es: "A partir del diseño se talla un modelo de cera — la forma exacta que adoptará después el metal.",
    },
  },

  {
    image: "/images/bespoke/step-05.jpg",
    imageAlt:
      "Molten metal being poured during the casting process",
    title: {
      de: "Guss",
      en: "Casting",
      tr: "Döküm",
      sk: "Odlievanie",
      cs: "Odlévání",
      hu: "Öntés",
      pl: "Odlewanie",
      ru: "Литьё",
      nl: "Gieten",
      da: "Støbning",
      fi: "Valu",
      sv: "Gjutning",
      fr: "Coulée",
      it: "Fusione",
      es: "Fundición",
    },
    description: {
      de: "Das Metall wird geschmolzen und von Hand aus dem Wachsmodell in unserer Werkstatt gegossen.",
      en: "The metal is cast from the wax model, molten and poured by hand in our workshop.",
      tr: "Metal, balmumu modelden dökülür — atölyemizde elle eritilip dökülür.",
      sk: "Kov sa odleje podľa voskového modelu — v našej dielni ho ručne roztavíme a odlejeme.",
      cs: "Kov se odlije podle voskového modelu — v naší dílně ho ručně roztavíme a odlijeme.",
      hu: "A fémet a viaszmodell alapján öntjük — műhelyünkben kézzel olvasztjuk és öntjük.",
      pl: "Metal jest odlewany na podstawie modelu woskowego — topiony i odlewany ręcznie w naszym warsztacie.",
      ru: "Металл плавится и вручную отливается в нашей мастерской по восковой модели.",
      nl: "Het metaal wordt in ons atelier gesmolten en met de hand gegoten op basis van het wasmodel.",
      da: "Metallet smeltes og støbes i hånden i vores værksted ud fra voksmodellen.",
      fi: "Metalli sulatetaan ja valetaan käsin omassa verstaassamme vahamallin pohjalta.",
      sv: "Metallen smälts och gjuts för hand i vår verkstad utifrån vaxmodellen.",
      fr: "Le métal est fondu puis coulé à la main dans notre atelier à partir du modèle en cire.",
      it: "Il metallo viene fuso e colato a mano nel nostro laboratorio partendo dal modello in cera.",
      es: "El metal se funde y se vierte a mano en nuestro taller a partir del modelo de cera.",
    },
  },

  {
    image: "/images/bespoke/step-06.jpg",
    imageAlt:
      "Jeweller shaping the prongs of a ring to hold a stone",
    title: {
      de: "Fassung vorbereiten",
      en: "Shaping the Setting",
      tr: "Yuvayı Şekillendirme",
      sk: "Príprava objímky",
      cs: "Příprava objímky",
      hu: "A foglalat kialakítása",
      pl: "Kształtowanie oprawy",
      ru: "Формирование закрепки",
      nl: "De zetting vormen",
      da: "Formning af fatningen",
      fi: "Istutuksen muotoilu",
      sv: "Formning av infattningen",
      fr: "Façonnage du serti",
      it: "Preparazione dell’incastonatura",
      es: "Preparación del engaste",
    },
    description: {
      de: "Die Krappen werden geformt und angepasst, damit sie Ihren Stein sicher und schön halten.",
      en: "Prongs are shaped and fitted, built to hold your stone securely and beautifully.",
      tr: "Pençeler şekillendirilir ve yerleştirilir — taşınızı güvenli ve zarif bir şekilde tutacak şekilde.",
      sk: "Kotlíky sa tvarujú a upravujú tak, aby váš kameň bezpečne a krásne držali.",
      cs: "Kotlíky se tvarují a upravují tak, aby váš kámen bezpečně a krásně držely.",
      hu: "A karmokat úgy alakítjuk és illesztjük, hogy biztonságosan és szépen tartsák a követ.",
      pl: "Ząbki są kształtowane i dopasowywane tak, by bezpiecznie i pięknie utrzymać Twój kamień.",
      ru: "Крапаны формируются и подгоняются так, чтобы надёжно и красиво удерживать ваш камень.",
      nl: "De griffen worden gevormd en aangepast zodat ze uw steen veilig en elegant op zijn plaats houden.",
      da: "Fatningens greb formes og tilpasses, så stenen holdes sikkert og smukt på plads.",
      fi: "Kynnet muotoillaan ja sovitetaan niin, että kivi pysyy turvallisesti ja kauniisti paikallaan.",
      sv: "Klorna formas och anpassas för att hålla stenen säkert och vackert på plats.",
      fr: "Les griffes sont façonnées et ajustées pour maintenir votre pierre avec sécurité et élégance.",
      it: "Le griffe vengono modellate e adattate per sostenere la pietra in modo sicuro ed elegante.",
      es: "Las garras se moldean y ajustan para sujetar la piedra con seguridad y elegancia.",
    },
  },

  {
    image: "/images/bespoke/step-07.jpg",
    imageAlt:
      "Jeweller carefully setting a diamond into a ring with tweezers",
    title: {
      de: "Stein fassen",
      en: "Setting the Stone",
      tr: "Taşı Yerleştirme",
      sk: "Osadenie kameňa",
      cs: "Osazení kamene",
      hu: "A kő befoglalása",
      pl: "Osadzanie kamienia",
      ru: "Закрепка камня",
      nl: "De steen zetten",
      da: "Fatning af stenen",
      fi: "Kiven istutus",
      sv: "Infattning av stenen",
      fr: "Sertissage de la pierre",
      it: "Incastonatura della pietra",
      es: "Engaste de la piedra",
    },
    description: {
      de: "Der Stein wird von Hand gefasst, geprüft und justiert, bis er perfekt sitzt.",
      en: "The stone is set by hand, checked and adjusted until it sits perfectly.",
      tr: "Taş elle yerleştirilir, mükemmel oturana kadar kontrol edilir ve ayarlanır.",
      sk: "Kameň sa osadzuje ručne, kontroluje a dolaďuje, kým nesedí dokonale.",
      cs: "Kámen se osazuje ručně, kontroluje a dolaďuje, dokud nesedí dokonale.",
      hu: "A követ kézzel foglalják be, ellenőrzik és igazítják, amíg tökéletesen nem illeszkedik.",
      pl: "Kamień jest osadzany ręcznie, sprawdzany i regulowany, aż idealnie się ułoży.",
      ru: "Камень закрепляется вручную, проверяется и регулируется до идеальной посадки.",
      nl: "De steen wordt met de hand gezet, gecontroleerd en aangepast tot hij perfect zit.",
      da: "Stenen sættes i hånden, kontrolleres og justeres, indtil den sidder perfekt.",
      fi: "Kivi istutetaan käsin, tarkistetaan ja säädetään, kunnes se istuu täydellisesti.",
      sv: "Stenen fattas för hand, kontrolleras och justeras tills den sitter perfekt.",
      fr: "La pierre est sertie à la main, contrôlée puis ajustée jusqu’à ce qu’elle soit parfaitement positionnée.",
      it: "La pietra viene incastonata a mano, controllata e regolata finché non risulta perfettamente posizionata.",
      es: "La piedra se engasta a mano, se revisa y se ajusta hasta quedar perfectamente colocada.",
    },
  },

  {
    image: "/images/bespoke/step-08.jpg",
    imageAlt: "Ring being polished on a polishing wheel",
    title: {
      de: "Polieren",
      en: "Polishing",
      tr: "Parlatma",
      sk: "Leštenie",
      cs: "Leštění",
      hu: "Polírozás",
      pl: "Polerowanie",
      ru: "Полировка",
      nl: "Polijsten",
      da: "Polering",
      fi: "Kiillotus",
      sv: "Polering",
      fr: "Polissage",
      it: "Lucidatura",
      es: "Pulido",
    },
    description: {
      de: "Das Stück wird auf Hochglanz poliert, um seine volle Brillanz zu entfalten.",
      en: "The piece is polished to a mirror finish, bringing out its full brilliance.",
      tr: "Parça, tüm parlaklığını ortaya çıkaracak şekilde ayna gibi parlatılır.",
      sk: "Šperk sa vyleští do zrkadlového lesku, aby vynikla jeho plná brilancia.",
      cs: "Šperk se vyleští do zrcadlového lesku, aby vynikla jeho plná brilance.",
      hu: "A darabot tükörfényesre polírozzuk, hogy teljes ragyogása kibontakozzon.",
      pl: "Element jest polerowany na wysoki połysk, aby uwydatnić jego pełny blask.",
      ru: "Украшение полируется до зеркального блеска, раскрывая всё своё сияние.",
      nl: "Het sieraad wordt tot een spiegelglans gepolijst zodat zijn volledige schittering zichtbaar wordt.",
      da: "Smykket poleres til spejlglans, så dets fulde brilliance kommer frem.",
      fi: "Koru kiillotetaan peilimäiseen kiiltoon, jotta sen koko loisto pääsee esiin.",
      sv: "Smycket poleras till spegelglans för att framhäva hela dess lyster.",
      fr: "La pièce est polie jusqu’à obtenir un effet miroir qui révèle tout son éclat.",
      it: "Il gioiello viene lucidato a specchio per esaltarne tutta la brillantezza.",
      es: "La pieza se pule hasta obtener un acabado espejo que realza todo su brillo.",
    },
  },
];

export const PHASE_3_STEPS: BespokeStep[] = [
  {
    image: "/images/bespoke/step-09.jpg",
    imageAlt:
      "Jeweller inspecting a finished ring with a loupe, wearing white gloves",
    title: {
      de: "Qualitätsprüfung",
      en: "Quality Inspection",
      tr: "Kalite Kontrolü",
      sk: "Kontrola kvality",
      cs: "Kontrola kvality",
      hu: "Minőségellenőrzés",
      pl: "Kontrola jakości",
      ru: "Контроль качества",
      nl: "Kwaliteitscontrole",
      da: "Kvalitetskontrol",
      fi: "Laaduntarkastus",
      sv: "Kvalitetskontroll",
      fr: "Contrôle qualité",
      it: "Controllo qualità",
      es: "Control de calidad",
    },
    description: {
      de: "Jedes Detail wird unter Vergrößerung geprüft — nichts verlässt unsere Werkstatt ungeprüft.",
      en: "Every detail is checked under magnification — nothing leaves our workshop unchecked.",
      tr: "Her detay büyüteç altında kontrol edilir — hiçbir şey atölyemizden kontrolsüz çıkmaz.",
      sk: "Každý detail kontrolujeme pod zväčšením — z našej dielne neodíde nič neskontrolované.",
      cs: "Každý detail kontrolujeme pod zvětšením — z naší dílny neodejde nic nezkontrolované.",
      hu: "Minden részletet nagyítás alatt ellenőrzünk — semmi nem hagyja el a műhelyünket ellenőrzés nélkül.",
      pl: "Każdy detal sprawdzamy pod powiększeniem — nic nie opuszcza naszego warsztatu bez kontroli.",
      ru: "Каждая деталь проверяется под увеличением — ни одно украшение не покидает нашу мастерскую без контроля.",
      nl: "Elk detail wordt onder vergroting gecontroleerd — niets verlaat ons atelier zonder inspectie.",
      da: "Hver detalje kontrolleres under forstørrelse — intet forlader vores værksted uden kontrol.",
      fi: "Jokainen yksityiskohta tarkistetaan suurennettuna — mikään ei poistu verstaastamme ilman tarkastusta.",
      sv: "Varje detalj kontrolleras under förstoring — inget lämnar vår verkstad utan kontroll.",
      fr: "Chaque détail est contrôlé sous grossissement — aucune pièce ne quitte notre atelier sans inspection.",
      it: "Ogni dettaglio viene controllato sotto ingrandimento — nulla lascia il nostro laboratorio senza verifica.",
      es: "Cada detalle se revisa con aumento — ninguna pieza sale de nuestro taller sin ser inspeccionada.",
    },
  },

  {
    image: "/images/bespoke/step-10.jpg",
    imageAlt:
      "Jeweller applying final finishing touches to a ring",
    title: {
      de: "Letzter Schliff",
      en: "Final Finishing",
      tr: "Son Rötuşlar",
      sk: "Finálne dokončenie",
      cs: "Finální dokončení",
      hu: "Végső simítások",
      pl: "Ostatnie poprawki",
      ru: "Финальная отделка",
      nl: "Laatste afwerking",
      da: "Sidste finish",
      fi: "Viimeinen viimeistely",
      sv: "Slutlig finish",
      fr: "Finitions finales",
      it: "Finitura finale",
      es: "Acabado final",
    },
    description: {
      de: "Letzte Handgriffe und Anpassungen, damit sich das Stück genau richtig anfühlt.",
      en: "Final touches and adjustments, so the piece feels exactly right.",
      tr: "Parçanın tam olarak doğru hissettirmesi için son dokunuşlar ve ayarlamalar yapılır.",
      sk: "Posledné úpravy a doladenia, aby šperk sedel presne tak, ako má.",
      cs: "Poslední úpravy a doladění, aby šperk seděl přesně tak, jak má.",
      hu: "Utolsó igazítások és finomítások, hogy a darab pontosan úgy érződjön, ahogy kell.",
      pl: "Ostatnie poprawki i regulacje, aby element czuł się dokładnie tak, jak powinien.",
      ru: "Последние штрихи и корректировки делают украшение именно таким, каким оно должно быть.",
      nl: "De laatste details en aanpassingen zorgen ervoor dat het sieraad precies goed aanvoelt.",
      da: "De sidste detaljer og justeringer sikrer, at smykket føles helt rigtigt.",
      fi: "Viimeiset viimeistelyt ja säädöt varmistavat, että koru tuntuu juuri oikealta.",
      sv: "De sista detaljerna och justeringarna gör att smycket känns precis rätt.",
      fr: "Les dernières retouches et ajustements permettent à la pièce d’être exactement comme elle doit être.",
      it: "Gli ultimi ritocchi e le regolazioni finali assicurano che il gioiello risulti esattamente come desiderato.",
      es: "Los últimos retoques y ajustes hacen que la pieza resulte exactamente como debe ser.",
    },
  },

  {
    image: "/images/bespoke/step-11.jpg",
    imageAlt:
      "Finished ring presented in an open velvet box with ribbon",
    title: {
      de: "Präsentation",
      en: "Presentation",
      tr: "Sunum",
      sk: "Prezentácia",
      cs: "Prezentace",
      hu: "Bemutatás",
      pl: "Prezentacja",
      ru: "Презентация",
      nl: "Presentatie",
      da: "Præsentation",
      fi: "Esittely",
      sv: "Presentation",
      fr: "Présentation",
      it: "Presentazione",
      es: "Presentación",
    },
    description: {
      de: "Ihr Stück wird in seiner Box präsentiert, bereit für den Moment, für den es gemacht wurde.",
      en: "Your piece is presented in its box, ready for the moment it was made for.",
      tr: "Parçanız kutusunda sunulur — yapıldığı o an için hazır.",
      sk: "Váš šperk je uložený vo svojej krabičke, pripravený na chvíľu, pre ktorú bol stvorený.",
      cs: "Váš šperk je uložený ve své krabičce, připravený na chvíli, pro kterou byl stvořen.",
      hu: "Az Ön darabja a dobozában várja, hogy elérkezzen az a pillanat, amelyre készült.",
      pl: "Twój element prezentowany jest w pudełku, gotowy na chwilę, dla której powstał.",
      ru: "Ваше украшение представлено в своей коробке и готово к тому моменту, ради которого оно было создано.",
      nl: "Uw sieraad wordt in zijn doos gepresenteerd, klaar voor het moment waarvoor het is gemaakt.",
      da: "Dit smykke præsenteres i sin æske, klar til det øjeblik, det blev skabt til.",
      fi: "Korusi esitellään omassa rasiassaan valmiina siihen hetkeen, jota varten se luotiin.",
      sv: "Ditt smycke presenteras i sin ask, redo för det ögonblick det skapades för.",
      fr: "Votre bijou est présenté dans son écrin, prêt pour le moment auquel il était destiné.",
      it: "Il vostro gioiello viene presentato nel suo cofanetto, pronto per il momento per cui è stato creato.",
      es: "Su joya se presenta en su estuche, lista para el momento para el que fue creada.",
    },
  },

  {
    image: "/images/bespoke/step-12.png",
    imageAlt:
      "The finished ring being handed over to the client in its box",
    title: {
      de: "Übergabe",
      en: "Delivery",
      tr: "Teslimat",
      sk: "Odovzdanie",
      cs: "Předání",
      hu: "Átadás",
      pl: "Wydanie",
      ru: "Передача",
      nl: "Oplevering",
      da: "Levering",
      fi: "Luovutus",
      sv: "Leverans",
      fr: "Remise",
      it: "Consegna",
      es: "Entrega",
    },
    description: {
      de: "Übergeben an Sie — ein Stück, das für niemand anderen gemacht wurde, genau so, wie Sie es sich vorgestellt haben.",
      en: "Delivered to you — a piece made for no one else, exactly as you imagined it.",
      tr: "Size teslim edilir — başka hiç kimse için yapılmamış, tam olarak hayal ettiğiniz gibi bir parça.",
      sk: "Odovzdaný vám — šperk, ktorý nevznikol pre nikoho iného, presne taký, aký ste si predstavovali.",
      cs: "Předaný vám — šperk, který nevznikl pro nikoho jiného, přesně takový, jaký jste si představovali.",
      hu: "Önnek átadva — egy darab, amit senki másnak nem készítettek, pontosan úgy, ahogy elképzelte.",
      pl: "Wręczony Tobie — element stworzony wyłącznie dla Ciebie, dokładnie taki, jak sobie wyobrażałeś.",
      ru: "Передано вам — украшение, созданное только для вас, именно таким, каким вы его представляли.",
      nl: "Aan u overhandigd — een sieraad dat voor niemand anders is gemaakt, precies zoals u het zich had voorgesteld.",
      da: "Overdraget til dig — et smykke skabt til ingen andre, præcis som du forestillede dig det.",
      fi: "Luovutetaan sinulle — koru, jota ei ole tehty kenellekään muulle, juuri sellaisena kuin kuvittelit.",
      sv: "Överlämnat till dig — ett smycke skapat för ingen annan, precis som du föreställde dig det.",
      fr: "Remis entre vos mains — un bijou créé pour personne d’autre, exactement comme vous l’aviez imaginé.",
      it: "Consegnato a voi — un gioiello creato per nessun altro, esattamente come lo avevate immaginato.",
      es: "Entregada a usted — una pieza creada para nadie más, exactamente como la había imaginado.",
    },
  },
];