import type { Locale } from "./i18n";

type LocalizedText = Partial<Record<Locale, string>>;

export const DESIGN_TEXT: Record<string, LocalizedText> = {
  heroEyebrow: {
    de: "Design",
    en: "Design",
    tr: "Tasarım",
    sk: "Dizajn",
    cs: "Design",
    hu: "Design",
    pl: "Design",
    ru: "Дизайн",
    nl: "Design",
    da: "Design",
    fi: "Design",
    sv: "Design",
    fr: "Design",
    it: "Design",
    es: "Diseño",
  },

  heroTitle: {
    de: "Jede Saison eine neue Kollektion",
    en: "A New Collection, Every Season",
    tr: "Her Mevsim Yeni Bir Koleksiyon",
    sk: "Každú sezónu nová kolekcia",
    cs: "Každou sezónu nová kolekce",
    hu: "Minden évszakban új kollekció",
    pl: "Każdy sezon to nowa kolekcja",
    ru: "Новая коллекция каждый сезон",
    nl: "Elk seizoen een nieuwe collectie",
    da: "En ny kollektion hver sæson",
    fi: "Uusi mallisto jokaiseen vuodenaikaan",
    sv: "En ny kollektion varje säsong",
    fr: "Une nouvelle collection à chaque saison",
    it: "Una nuova collezione ogni stagione",
    es: "Una nueva colección cada temporada",
  },

  heroLead: {
    de: "Jedes Stück bei LIDYA JEWELRY wird bei uns entworfen und von Hand gefertigt. Viermal im Jahr — mit jedem Jahreszeitenwechsel — stellen wir eine neue Kollektion vor, damit es immer etwas Neues zu entdecken, zu tragen und zu verschenken gibt.",
    en: "Every piece at LIDYA JEWELRY is designed and handcrafted in-house. Four times a year — with the turn of each season — we introduce a new collection, so there's always something new to discover, wear and give.",
    tr: "LIDYA JEWELRY'deki her parça bizzat tasarlanır ve elde işlenir. Yılda dört kez — her mevsim dönümünde — yeni bir koleksiyon sunuyoruz, böylece her zaman keşfedilecek, takılacak ve hediye edilecek yeni bir şey oluyor.",
    sk: "Každý kus v LIDYA JEWELRY navrhujeme a ručne vyrábame priamo u nás. Štyrikrát do roka — s príchodom každej sezóny — predstavujeme novú kolekciu, aby bolo vždy čo objavovať, nosiť a darovať.",
    cs: "Každý kus v LIDYA JEWELRY navrhujeme a ručně vyrábíme přímo u nás. Čtyřikrát do roka — s příchodem každé sezóny — představujeme novou kolekci, aby bylo vždy co objevovat, nosit a darovat.",
    hu: "A LIDYA JEWELRY minden darabját mi magunk tervezzük és kézzel készítjük. Évente négyszer — minden évszakváltáskor — új kollekciót mutatunk be, hogy mindig legyen mit felfedezni, viselni és ajándékozni.",
    pl: "Każdy element w LIDYA JEWELRY projektujemy i wykonujemy ręcznie we własnym atelier. Cztery razy w roku — wraz ze zmianą pory roku — prezentujemy nową kolekcję, dzięki czemu zawsze jest coś nowego do odkrycia, noszenia i podarowania.",
    ru: "Каждое украшение LIDYA JEWELRY разрабатывается и изготавливается вручную в нашей мастерской. Четыре раза в год — с наступлением каждого нового сезона — мы представляем новую коллекцию, чтобы всегда было что-то новое для открытия, ношения и подарка.",
    nl: "Elk sieraad van LIDYA JEWELRY wordt door ons ontworpen en met de hand vervaardigd. Vier keer per jaar — bij het begin van elk nieuw seizoen — presenteren we een nieuwe collectie, zodat er altijd iets nieuws te ontdekken, te dragen en cadeau te geven is.",
    da: "Hvert smykke hos LIDYA JEWELRY bliver designet og håndlavet hos os. Fire gange om året — ved hvert sæsonskifte — præsenterer vi en ny kollektion, så der altid er noget nyt at opdage, bære og give som gave.",
    fi: "Jokainen LIDYA JEWELRY -koru suunnitellaan ja valmistetaan käsin omassa verstaassamme. Neljä kertaa vuodessa — vuodenaikojen vaihtuessa — esittelemme uuden malliston, joten aina löytyy jotain uutta löydettäväksi, käytettäväksi ja lahjaksi annettavaksi.",
    sv: "Varje smycke hos LIDYA JEWELRY designas och tillverkas för hand hos oss. Fyra gånger om året — vid varje säsongsskifte — presenterar vi en ny kollektion, så att det alltid finns något nytt att upptäcka, bära och ge bort.",
    fr: "Chaque pièce LIDYA JEWELRY est conçue et fabriquée à la main dans notre propre atelier. Quatre fois par an — à chaque changement de saison — nous présentons une nouvelle collection, afin qu’il y ait toujours quelque chose de nouveau à découvrir, à porter et à offrir.",
    it: "Ogni gioiello LIDYA JEWELRY viene progettato e realizzato a mano nel nostro laboratorio. Quattro volte all’anno — a ogni cambio di stagione — presentiamo una nuova collezione, così c’è sempre qualcosa di nuovo da scoprire, indossare e regalare.",
    es: "Cada pieza de LIDYA JEWELRY se diseña y elabora a mano en nuestro propio taller. Cuatro veces al año — con cada cambio de estación — presentamos una nueva colección, para que siempre haya algo nuevo que descubrir, llevar y regalar.",
  },

  sectionEyebrow: {
    de: "Die vier Kollektionen",
    en: "The Four Collections",
    tr: "Dört Koleksiyon",
    sk: "Štyri kolekcie",
    cs: "Čtyři kolekce",
    hu: "A négy kollekció",
    pl: "Cztery kolekcje",
    ru: "Четыре коллекции",
    nl: "De vier collecties",
    da: "De fire kollektioner",
    fi: "Neljä mallistoa",
    sv: "De fyra kollektionerna",
    fr: "Les quatre collections",
    it: "Le quattro collezioni",
    es: "Las cuatro colecciones",
  },

  sectionTitle: {
    de: "Frühling, Sommer, Herbst, Winter",
    en: "Spring, Summer, Autumn, Winter",
    tr: "İlkbahar, Yaz, Sonbahar, Kış",
    sk: "Jar, leto, jeseň, zima",
    cs: "Jaro, léto, podzim, zima",
    hu: "Tavasz, nyár, ősz, tél",
    pl: "Wiosna, lato, jesień, zima",
    ru: "Весна, лето, осень, зима",
    nl: "Lente, zomer, herfst, winter",
    da: "Forår, sommer, efterår, vinter",
    fi: "Kevät, kesä, syksy, talvi",
    sv: "Vår, sommar, höst, vinter",
    fr: "Printemps, été, automne, hiver",
    it: "Primavera, estate, autunno, inverno",
    es: "Primavera, verano, otoño, invierno",
  },

  ctaTitle: {
    de: "Entdecken Sie die aktuelle Kollektion",
    en: "Discover the Current Collection",
    tr: "Güncel Koleksiyonu Keşfedin",
    sk: "Objavte aktuálnu kolekciu",
    cs: "Objevte aktuální kolekci",
    hu: "Fedezze fel az aktuális kollekciót",
    pl: "Odkryj aktualną kolekcję",
    ru: "Откройте для себя актуальную коллекцию",
    nl: "Ontdek de huidige collectie",
    da: "Oplev den aktuelle kollektion",
    fi: "Tutustu tämänhetkiseen mallistoon",
    sv: "Upptäck den aktuella kollektionen",
    fr: "Découvrez la collection actuelle",
    it: "Scoprite la collezione attuale",
    es: "Descubra la colección actual",
  },

  ctaSub: {
    de: "Besuchen Sie eine unserer Boutiquen oder vereinbaren Sie einen privaten Termin, um die neueste Saisonkollektion in Person zu sehen.",
    en: "Visit one of our boutiques or book a private appointment to see the latest seasonal collection in person.",
    tr: "En son sezon koleksiyonunu birebir görmek için butiklerimizden birini ziyaret edin veya özel bir randevu alın.",
    sk: "Navštívte niektorý z našich butikov alebo si dohodnite súkromné stretnutie a pozrite si najnovšiu sezónnu kolekciu naživo.",
    cs: "Navštivte některý z našich butiků nebo si domluvte soukromou schůzku a prohlédněte si nejnovější sezónní kolekci naživo.",
    hu: "Látogasson el valamelyik butikunkba, vagy foglaljon privát időpontot, hogy személyesen is megtekinthesse a legújabb szezonális kollekciót.",
    pl: "Odwiedź jeden z naszych butików lub umów się na prywatne spotkanie, aby zobaczyć najnowszą kolekcję sezonową osobiście.",
    ru: "Посетите один из наших бутиков или запишитесь на индивидуальную встречу, чтобы лично увидеть новейшую сезонную коллекцию.",
    nl: "Bezoek een van onze boetieks of maak een privéafspraak om de nieuwste seizoenscollectie persoonlijk te bekijken.",
    da: "Besøg en af vores boutiques eller book en privat aftale for at opleve den nyeste sæsonkollektion personligt.",
    fi: "Vieraile yhdessä myymälöistämme tai varaa yksityinen tapaaminen nähdäksesi uusimman kausimalliston paikan päällä.",
    sv: "Besök en av våra butiker eller boka ett privat möte för att se den senaste säsongskollektionen på plats.",
    fr: "Visitez l’une de nos boutiques ou prenez rendez-vous en privé pour découvrir personnellement notre toute dernière collection saisonnière.",
    it: "Visitate una delle nostre boutique o prenotate un appuntamento privato per scoprire di persona l’ultima collezione stagionale.",
    es: "Visite una de nuestras boutiques o reserve una cita privada para descubrir en persona la última colección de temporada.",
  },
};

export type Season = {
  id: "spring" | "summer" | "autumn" | "winter";
  name: LocalizedText;
  description: LocalizedText;
  image: string;
  imageAlt: string;
};

export const SEASONS: Season[] = [
  {
    id: "spring",
    image: "/images/design/spring.jpg",
    imageAlt: "Spring collection — floral-inspired jewellery moodboard",
    name: {
      de: "Frühlingskollektion",
      en: "Spring Collection",
      tr: "İlkbahar Koleksiyonu",
      sk: "Jarná kolekcia",
      cs: "Jarní kolekce",
      hu: "Tavaszi kollekció",
      pl: "Kolekcja wiosenna",
      ru: "Весенняя коллекция",
      nl: "Lentecollectie",
      da: "Forårskollektion",
      fi: "Kevätmallisto",
      sv: "Vårkollektion",
      fr: "Collection printemps",
      it: "Collezione primavera",
      es: "Colección de primavera",
    },
    description: {
      de: "Leichte, frische Stücke, inspiriert von den ersten Farben der Saison — zarte Blütenmotive und sanfte Steine.",
      en: "Light, fresh pieces inspired by the first colours of the season — delicate florals and soft stones.",
      tr: "Sezonun ilk renklerinden ilham alan hafif, taze parçalar — narin çiçek motifleri ve yumuşak taşlar.",
      sk: "Ľahké, svieže kúsky inšpirované prvými farbami sezóny — jemné kvetinové motívy a nežné odtiene kameňov.",
      cs: "Lehké, svěží kousky inspirované prvními barvami sezóny — jemné květinové motivy a něžné odstíny kamenů.",
      hu: "Könnyed, friss darabok, a szezon első színei ihlették — finom virágmotívumok és lágy árnyalatú kövek.",
      pl: "Lekkie, świeże elementy inspirowane pierwszymi barwami sezonu — delikatne motywy kwiatowe i kamienie w subtelnych odcieniach.",
      ru: "Лёгкие, свежие украшения, вдохновлённые первыми красками сезона — нежные цветочные мотивы и камни мягких оттенков.",
      nl: "Lichte, frisse sieraden geïnspireerd op de eerste kleuren van het seizoen — verfijnde bloemmotieven en stenen in zachte tinten.",
      da: "Lette, friske smykker inspireret af sæsonens første farver — fine blomstermotiver og sten i bløde nuancer.",
      fi: "Kevyet ja raikkaat korut saavat inspiraationsa kauden ensimmäisistä väreistä — herkkiä kukka-aiheita ja pehmeän sävyisiä kiviä.",
      sv: "Lätta, fräscha smycken inspirerade av säsongens första färger — fina blommotiv och stenar i mjuka nyanser.",
      fr: "Des pièces légères et fraîches inspirées des premières couleurs de la saison — motifs floraux délicats et pierres aux teintes douces.",
      it: "Gioielli leggeri e freschi ispirati ai primi colori della stagione — delicati motivi floreali e pietre dalle tonalità morbide.",
      es: "Piezas ligeras y frescas inspiradas en los primeros colores de la temporada — delicados motivos florales y piedras de tonos suaves.",
    },
  },

  {
    id: "summer",
    image: "/images/design/summer.jpg",
    imageAlt: "Summer collection — beach and sea-inspired jewellery moodboard",
    name: {
      de: "Sommerkollektion",
      en: "Summer Collection",
      tr: "Yaz Koleksiyonu",
      sk: "Letná kolekcia",
      cs: "Letní kolekce",
      hu: "Nyári kollekció",
      pl: "Kolekcja letnia",
      ru: "Летняя коллекция",
      nl: "Zomercollectie",
      da: "Sommerkollektion",
      fi: "Kesämallisto",
      sv: "Sommarkollektion",
      fr: "Collection été",
      it: "Collezione estate",
      es: "Colección de verano",
    },
    description: {
      de: "Strahlende, leuchtende Designs für lange Tage und warme Abende am Meer.",
      en: "Bright, radiant designs made for long days and warm evenings by the sea.",
      tr: "Uzun günler ve denizde geçen sıcak akşamlar için parlak, ışıltılı tasarımlar.",
      sk: "Žiarivé, výrazné dizajny stvorené pre dlhé dni a teplé večery pri mori.",
      cs: "Zářivé, výrazné designy stvořené pro dlouhé dny a teplé večery u moře.",
      hu: "Ragyogó, sugárzó dizájnok a hosszú napokra és a tengerparti meleg estékre.",
      pl: "Jasne, promienne wzory stworzone na długie dni i ciepłe wieczory nad morzem.",
      ru: "Яркие, сияющие дизайны для долгих дней и тёплых вечеров у моря.",
      nl: "Heldere, stralende ontwerpen voor lange dagen en warme avonden aan zee.",
      da: "Lyse, strålende designs skabt til lange dage og varme aftener ved havet.",
      fi: "Kirkkaat ja säteilevät mallit pitkiin päiviin ja lämpimiin iltoihin meren äärellä.",
      sv: "Ljusa, strålande designer skapade för långa dagar och varma kvällar vid havet.",
      fr: "Des créations lumineuses et éclatantes pensées pour les longues journées et les soirées chaudes au bord de la mer.",
      it: "Design luminosi e radiosi pensati per lunghe giornate e calde serate sul mare.",
      es: "Diseños luminosos y radiantes creados para largos días y cálidas noches junto al mar.",
    },
  },

  {
    id: "autumn",
    image: "/images/design/autumn.jpg",
    imageAlt: "Autumn collection — golden leaf-inspired jewellery moodboard",
    name: {
      de: "Herbstkollektion",
      en: "Autumn Collection",
      tr: "Sonbahar Koleksiyonu",
      sk: "Jesenná kolekcia",
      cs: "Podzimní kolekce",
      hu: "Őszi kollekció",
      pl: "Kolekcja jesienna",
      ru: "Осенняя коллекция",
      nl: "Herfstcollectie",
      da: "Efterårskollektion",
      fi: "Syysmallisto",
      sv: "Höstkollektion",
      fr: "Collection automne",
      it: "Collezione autunno",
      es: "Colección de otoño",
    },
    description: {
      de: "Wärmere Töne und reichere Texturen, inspiriert von goldenem Licht und fallendem Laub.",
      en: "Warmer tones and richer textures, inspired by golden light and turning leaves.",
      tr: "Altın ışık ve renk değiştiren yapraklardan ilham alan daha sıcak tonlar ve daha zengin dokular.",
      sk: "Teplejšie tóny a bohatšie textúry, inšpirované zlatým svetlom a farbiacim sa lístím.",
      cs: "Teplejší tóny a bohatší textury, inspirované zlatým světlem a barvícím se listím.",
      hu: "Melegebb tónusok és gazdagabb textúrák, az aranyfény és a színesedő levelek ihlették.",
      pl: "Cieplejsze tony i bogatsze faktury, inspirowane złotym światłem i mieniącymi się liśćmi.",
      ru: "Более тёплые оттенки и богатые текстуры, вдохновлённые золотым светом и меняющейся листвой.",
      nl: "Warmere tinten en rijkere texturen, geïnspireerd door gouden licht en verkleurende bladeren.",
      da: "Varmere toner og rigere teksturer inspireret af gyldent lys og blade, der skifter farve.",
      fi: "Lämpimämmät sävyt ja rikkaammat tekstuurit saavat inspiraationsa kultaisesta valosta ja väriään vaihtavista lehdistä.",
      sv: "Varmare toner och rikare texturer inspirerade av gyllene ljus och löv som skiftar färg.",
      fr: "Des tons plus chauds et des textures plus riches, inspirés par la lumière dorée et les feuilles qui changent de couleur.",
      it: "Tonalità più calde e texture più ricche, ispirate alla luce dorata e alle foglie che cambiano colore.",
      es: "Tonos más cálidos y texturas más ricas, inspirados en la luz dorada y las hojas que cambian de color.",
    },
  },

  {
    id: "winter",
    image: "/images/design/winter.jpg",
    imageAlt: "Winter collection — snowflake-inspired jewellery moodboard",
    name: {
      de: "Winterkollektion",
      en: "Winter Collection",
      tr: "Kış Koleksiyonu",
      sk: "Zimná kolekcia",
      cs: "Zimní kolekce",
      hu: "Téli kollekció",
      pl: "Kolekcja zimowa",
      ru: "Зимняя коллекция",
      nl: "Wintercollectie",
      da: "Vinterkollektion",
      fi: "Talvimallisto",
      sv: "Vinterkollektion",
      fr: "Collection hiver",
      it: "Collezione inverno",
      es: "Colección de invierno",
    },
    description: {
      de: "Kühne, strahlende Stücke für die Festtage — Statement-Schmuck für besondere Anlässe.",
      en: "Bold, luminous pieces for the festive season — statement jewellery for celebration.",
      tr: "Bayram sezonu için cesur, ışıltılı parçalar — kutlamalar için iddialı mücevherler.",
      sk: "Odvážne, žiarivé kúsky pre sviatočné obdobie — výrazné šperky na oslavy.",
      cs: "Odvážné, zářivé kousky pro sváteční období — výrazné šperky na oslavy.",
      hu: "Merész, ragyogó darabok az ünnepi szezonra — feltűnő ékszerek az ünneplésekhez.",
      pl: "Odważne, lśniące elementy na okres świąteczny — biżuteria na wyjątkowe okazje.",
      ru: "Смелые, сияющие украшения для праздничного сезона — выразительные изделия для особых моментов.",
      nl: "Gedurfde, stralende sieraden voor de feestdagen — opvallende juwelen voor bijzondere momenten.",
      da: "Dristige, strålende smykker til højtiden — markante smykker til særlige øjeblikke.",
      fi: "Rohkeat ja säteilevät korut juhlakautta varten — näyttäviä koruja erityisiin hetkiin.",
      sv: "Djärva, strålande smycken för högtiden — uttrycksfulla smycken för speciella tillfällen.",
      fr: "Des pièces audacieuses et lumineuses pour les fêtes — des bijoux de caractère pour les moments d’exception.",
      it: "Gioielli audaci e luminosi per il periodo delle feste — pezzi di carattere per le occasioni speciali.",
      es: "Piezas audaces y luminosas para la temporada festiva — joyas con carácter para momentos especiales.",
    },
  },
];