import type { Locale } from "./i18n";

type LocalizedText = Partial<Record<Locale, string>>;

export const GOLD_TEXT: Record<string, LocalizedText> = {
  heroEyebrow: {
    de: "Investmentgold",
    en: "Investment Gold",
    tr: "Yatırım Altını",
    sk: "Investičné zlato",
    cs: "Investiční zlato",
    hu: "Befektetési arany",
    pl: "Złoto inwestycyjne",
    ru: "Инвестиционное золото",
    nl: "Beleggingsgoud",
    da: "Investeringsguld",
    fi: "Sijoituskulta",
    sv: "Investeringsguld",
    fr: "Or d’investissement",
    it: "Oro da investimento",
    es: "Oro de inversión",
  },

  heroTitle: {
    de: "Physisches Gold, ganz nach Ihren Vorstellungen",
    en: "Physical Gold, Held Your Way",
    tr: "Fiziksel Altın, Size Özgü Şekilde",
    sk: "Fyzické zlato, presne podľa vás",
    cs: "Fyzické zlato, přesně podle vás",
    hu: "Fizikai arany, az Ön elképzelése szerint",
    pl: "Fizyczne złoto, dopasowane do Ciebie",
    ru: "Физическое золото — в удобной для вас форме",
    nl: "Fysiek goud, op uw manier",
    da: "Fysisk guld, på din måde",
    fi: "Fyysistä kultaa, juuri sinulle sopivalla tavalla",
    sv: "Fysiskt guld, på ditt sätt",
    fr: "De l’or physique, selon vos préférences",
    it: "Oro fisico, secondo le vostre esigenze",
    es: "Oro físico, a su manera",
  },

  heroLead: {
    de: "Von Gramm-Barren bis zum vollen Kilo, und Münzen von den führenden Prägestätten der Welt — jedes Stück, das wir anbieten, ist 999,9 Feingold, zertifiziert und bereit, als private, tragbare Wertanlage gehalten zu werden.",
    en: "From gram bars to a full kilo, and coins from the world's leading mints — every piece we offer is 999.9 fine gold, certified and ready to be held as a private, portable store of value.",
    tr: "Gram külçelerden tam kiloya, ve dünyanın önde gelen darphanelerinden sikkelere kadar — sunduğumuz her parça 999.9 saf altındır, sertifikalıdır ve özel, taşınabilir bir değer saklama aracı olarak tutulmaya hazırdır.",
    sk: "Od gramových tehličiek až po celé kilo, a mince od popredných svetových mincovní — každý kus, ktorý ponúkame, je rýdze zlato 999,9, certifikované a pripravené slúžiť ako súkromná, prenosná úschova hodnoty.",
    cs: "Od gramových cihliček až po celé kilo, a mince od předních světových mincoven — každý kus, který nabízíme, je ryzí zlato 999,9, certifikovaný a připravený sloužit jako soukromá, přenosná úschova hodnoty.",
    hu: "A gramm rúdaktól a teljes kilóig, valamint a világ vezető pénzverdéinek érméi — minden általunk kínált darab 999,9 finomságú arany, tanúsítvánnyal, magánjellegű, hordozható értékmegőrzőként készen áll.",
    pl: "Od sztabek jednogramowych po pełen kilogram, oraz monety z czołowych mennic świata — każdy oferowany przez nas element to złoto próby 999,9, certyfikowane i gotowe, by służyć jako prywatna, przenośna forma lokaty wartości.",
    ru: "От граммовых слитков до полного килограмма и монет ведущих мировых монетных дворов — каждое предлагаемое нами изделие изготовлено из золота 999,9 пробы, сертифицировано и может служить частным, портативным средством сохранения стоимости.",
    nl: "Van gramstaven tot een volledige kilo en munten van toonaangevende munthuizen wereldwijd — elk product dat wij aanbieden bestaat uit 999,9 fijn goud, is gecertificeerd en geschikt als persoonlijke, draagbare waardeopslag.",
    da: "Fra grambarer til et helt kilo og mønter fra verdens førende møntværker — hvert produkt, vi tilbyder, består af 999,9 fint guld, er certificeret og klar til at fungere som en privat, transportabel værdibeholdning.",
    fi: "Gramman harkoista aina kokonaiseen kiloon sekä maailman johtavien rahapajojen kolikoihin — jokainen tarjoamamme tuote on 999,9-pitoista kultaa, sertifioitu ja valmis toimimaan henkilökohtaisena, helposti siirrettävänä arvon säilyttäjänä.",
    sv: "Från gramstora tackor till ett helt kilo och mynt från världens ledande myntverk — varje produkt vi erbjuder består av 999,9 fint guld, är certifierad och redo att fungera som en privat, portabel värdebevarare.",
    fr: "Des lingots d’un gramme jusqu’au kilo complet, ainsi que des pièces provenant des plus grandes monnaies du monde — chaque produit que nous proposons est en or fin 999,9, certifié et prêt à constituer une réserve de valeur privée et transportable.",
    it: "Dai lingotti da un grammo fino al chilogrammo completo, oltre alle monete delle principali zecche mondiali — ogni prodotto che offriamo è in oro fino 999,9, certificato e pronto a fungere da riserva di valore privata e facilmente trasportabile.",
    es: "Desde lingotes de un gramo hasta un kilo completo, además de monedas de las principales casas de moneda del mundo — cada pieza que ofrecemos es oro fino 999,9, certificado y preparado para servir como reserva de valor privada y portátil.",
  },

  section1Eyebrow: {
    de: "Reinheit & Gewicht",
    en: "Purity & Weight",
    tr: "Saflık ve Ağırlık",
    sk: "Rýdzosť a váha",
    cs: "Ryzost a váha",
    hu: "Finomság és súly",
    pl: "Czystość i waga",
    ru: "Проба и вес",
    nl: "Zuiverheid & gewicht",
    da: "Renhed & vægt",
    fi: "Puhtaus & paino",
    sv: "Renhet & vikt",
    fr: "Pureté & poids",
    it: "Purezza & peso",
    es: "Pureza & peso",
  },

  section1Title: {
    de: "Was den Wert eines Barrens bestimmt",
    en: "What Determines a Bar's Value",
    tr: "Bir Külçenin Değerini Ne Belirler",
    sk: "Čo určuje hodnotu tehličky",
    cs: "Co určuje hodnotu cihličky",
    hu: "Mi határozza meg egy rúd értékét",
    pl: "Co decyduje o wartości sztabki",
    ru: "Что определяет стоимость слитка",
    nl: "Wat de waarde van een goudstaaf bepaalt",
    da: "Hvad bestemmer værdien af en guldbarre",
    fi: "Mikä määrittää kultaharkon arvon",
    sv: "Vad avgör värdet på en guldtacka",
    fr: "Ce qui détermine la valeur d’un lingot",
    it: "Cosa determina il valore di un lingotto",
    es: "Qué determina el valor de un lingote",
  },

  section2Eyebrow: {
    de: "Barren & Münzen",
    en: "Bars & Coins",
    tr: "Külçeler ve Sikkeler",
    sk: "Tehličky a mince",
    cs: "Cihličky a mince",
    hu: "Rudak és érmék",
    pl: "Sztabki i monety",
    ru: "Слитки и монеты",
    nl: "Goudstaven & munten",
    da: "Guldbarer & mønter",
    fi: "Harkot & kolikot",
    sv: "Tackor & mynt",
    fr: "Lingots & pièces",
    it: "Lingotti & monete",
    es: "Lingotes & monedas",
  },

  section2Title: {
    de: "Zwei Wege, Gold zu halten",
    en: "Two Ways to Hold Gold",
    tr: "Altın Tutmanın İki Yolu",
    sk: "Dva spôsoby, ako držať zlato",
    cs: "Dva způsoby, jak držet zlato",
    hu: "Kétféleképpen tarthatja az aranyat",
    pl: "Dwa sposoby na posiadanie złota",
    ru: "Два способа владеть золотом",
    nl: "Twee manieren om goud te bezitten",
    da: "To måder at eje guld på",
    fi: "Kaksi tapaa omistaa kultaa",
    sv: "Två sätt att äga guld",
    fr: "Deux façons de détenir de l’or",
    it: "Due modi per detenere oro",
    es: "Dos formas de poseer oro",
  },

  section3Eyebrow: {
    de: "Zertifiziert & Sicher",
    en: "Certified & Secure",
    tr: "Sertifikalı ve Güvenli",
    sk: "Certifikované a bezpečné",
    cs: "Certifikované a bezpečné",
    hu: "Tanúsított és biztonságos",
    pl: "Certyfikowane i bezpieczne",
    ru: "Сертифицировано и безопасно",
    nl: "Gecertificeerd & veilig",
    da: "Certificeret & sikkert",
    fi: "Sertifioitu & turvallinen",
    sv: "Certifierat & säkert",
    fr: "Certifié & sécurisé",
    it: "Certificato & sicuro",
    es: "Certificado & seguro",
  },

  section3Title: {
    de: "Mit Vertrauen gekauft, mit Vertrauen gehalten",
    en: "Bought With Confidence, Held With Confidence",
    tr: "Güvenle Satın Alınır, Güvenle Saklanır",
    sk: "Kúpené s dôverou, uchovávané s dôverou",
    cs: "Koupené s důvěrou, uchovávané s důvěrou",
    hu: "Bizalommal vásárolva, bizalommal megőrizve",
    pl: "Kupione z zaufaniem, przechowywane z zaufaniem",
    ru: "Покупайте с уверенностью, храните с уверенностью",
    nl: "Met vertrouwen gekocht, met vertrouwen bewaard",
    da: "Købt med tillid, opbevaret med tillid",
    fi: "Osta luottavaisin mielin, säilytä luottavaisin mielin",
    sv: "Köpt med förtroende, förvarat med förtroende",
    fr: "Achetez en toute confiance, conservez en toute confiance",
    it: "Acquistato con fiducia, custodito con fiducia",
    es: "Comprado con confianza, conservado con confianza",
  },

  section4Eyebrow: {
    de: "Warum in Gold investieren",
    en: "Why Invest in Gold",
    tr: "Neden Altına Yatırım Yapmalı",
    sk: "Prečo investovať do zlata",
    cs: "Proč investovat do zlata",
    hu: "Miért érdemes aranyba fektetni",
    pl: "Dlaczego warto inwestować w złoto",
    ru: "Почему инвестируют в золото",
    nl: "Waarom beleggen in goud",
    da: "Hvorfor investere i guld",
    fi: "Miksi sijoittaa kultaan",
    sv: "Varför investera i guld",
    fr: "Pourquoi investir dans l’or",
    it: "Perché investire nell’oro",
    es: "Por qué invertir en oro",
  },

  section4Title: {
    de: "Ein Wertspeicher für jede Generation",
    en: "A Store of Value for Every Generation",
    tr: "Her Nesil İçin Bir Değer Saklama Aracı",
    sk: "Úschova hodnoty pre každú generáciu",
    cs: "Úschova hodnoty pro každou generaci",
    hu: "Értékmegőrző minden generáció számára",
    pl: "Lokata wartości dla każdego pokolenia",
    ru: "Средство сохранения стоимости для каждого поколения",
    nl: "Een waardeopslag voor elke generatie",
    da: "En værdibeholdning for enhver generation",
    fi: "Arvon säilyttäjä jokaiselle sukupolvelle",
    sv: "En värdebevarare för varje generation",
    fr: "Une réserve de valeur pour chaque génération",
    it: "Una riserva di valore per ogni generazione",
    es: "Una reserva de valor para cada generación",
  },

  ctaTitle: {
    de: "Sprechen Sie mit uns über Investmentgold",
    en: "Speak With Us About Investment Gold",
    tr: "Yatırım Altını Hakkında Bizimle Konuşun",
    sk: "Porozprávajte sa s nami o investičnom zlate",
    cs: "Promluvte si s námi o investičním zlatě",
    hu: "Beszéljen velünk a befektetési aranyról",
    pl: "Porozmawiaj z nami o złocie inwestycyjnym",
    ru: "Поговорите с нами об инвестиционном золоте",
    nl: "Praat met ons over beleggingsgoud",
    da: "Tal med os om investeringsguld",
    fi: "Keskustele kanssamme sijoituskullasta",
    sv: "Prata med oss om investeringsguld",
    fr: "Parlez-nous de l’or d’investissement",
    it: "Parlate con noi dell’oro da investimento",
    es: "Hable con nosotros sobre oro de inversión",
  },

  ctaSub: {
    de: "Vereinbaren Sie einen privaten Termin, um den aktuellen Bestand zu sehen, Gewichte und Preise zu besprechen oder eine individuelle Bestellung aufzugeben.",
    en: "Book a private appointment to see current stock, discuss weights and pricing, or place a custom order.",
    tr: "Mevcut stoku görmek, ağırlık ve fiyatlandırmayı görüşmek veya özel bir sipariş vermek için özel bir randevu alın.",
    sk: "Dohodnite si súkromné stretnutie, kde si pozriete aktuálnu ponuku, prejdeme váhy a ceny, alebo zadáte individuálnu objednávku.",
    cs: "Domluvte si soukromou schůzku, kde si prohlédnete aktuální nabídku, projdeme váhy a ceny, nebo zadáte individuální objednávku.",
    hu: "Foglaljon privát időpontot, hogy megtekinthesse aktuális készletünket, megbeszélhessük a súlyokat és az árakat, vagy egyedi rendelést adhasson le.",
    pl: "Umów się na prywatne spotkanie, aby zobaczyć aktualny stan, omówić wagi i ceny lub złożyć indywidualne zamówienie.",
    ru: "Запишитесь на индивидуальную встречу, чтобы ознакомиться с актуальным ассортиментом, обсудить вес и цены или оформить специальный заказ.",
    nl: "Maak een privéafspraak om de actuele voorraad te bekijken, gewichten en prijzen te bespreken of een speciale bestelling te plaatsen.",
    da: "Book en privat aftale for at se det aktuelle udvalg, drøfte vægte og priser eller afgive en individuel bestilling.",
    fi: "Varaa yksityinen tapaaminen nähdäksesi ajankohtaisen valikoiman, keskustellaksesi painoista ja hinnoista tai tehdäksesi yksilöllisen tilauksen.",
    sv: "Boka ett privat möte för att se aktuellt lager, diskutera vikter och priser eller göra en individuell beställning.",
    fr: "Prenez rendez-vous en privé pour découvrir le stock actuel, discuter des poids et des prix ou passer une commande personnalisée.",
    it: "Prenotate un appuntamento privato per vedere la disponibilità attuale, discutere pesi e prezzi oppure effettuare un ordine personalizzato.",
    es: "Reserve una cita privada para consultar la disponibilidad actual, hablar sobre pesos y precios o realizar un pedido personalizado.",
  },
};

export type ValuePoint = {
  title: LocalizedText;
  description: LocalizedText;
  image: string;
  imageWidth: number;
  imageHeight: number;
  imageAlt: string;
};

export const SECTION_1_POINTS: ValuePoint[] = [
  {
    title: {
      de: "Reinheit & Feingehalt",
      en: "Purity & Fineness",
      tr: "Saflık ve Ayar",
      sk: "Rýdzosť a čistota",
      cs: "Ryzost a čistota",
      hu: "Finomság és tisztaság",
      pl: "Czystość i próba",
      ru: "Чистота и проба",
      nl: "Zuiverheid & fijnheid",
      da: "Renhed & finhed",
      fi: "Puhtaus & pitoisuus",
      sv: "Renhet & finhalt",
      fr: "Pureté & titre",
      it: "Purezza & titolo",
      es: "Pureza & ley",
    },

    description: {
      de: "Jeder Barren und jede Münze, die wir anbieten, besteht aus 999,9 Feingold — 24 Karat, dem reinsten weltweit anerkannten Standard.",
      en: "Every bar and coin we offer is 999.9 fine gold — 24 karat, the purest standard recognised worldwide.",
      tr: "Sunduğumuz her külçe ve sikke 999.9 saf altındır — dünya çapında tanınan en saf standart olan 24 ayar.",
      sk: "Každá tehlička a minca, ktorú ponúkame, je rýdze zlato 999,9 — 24 karátov, najčistejší celosvetovo uznávaný štandard.",
      cs: "Každá cihlička a mince, kterou nabízíme, je ryzí zlato 999,9 — 24 karátů, nejčistší celosvětově uznávaný standard.",
      hu: "Minden általunk kínált rúd és érme 999,9 finomságú arany — 24 karátos, a világszerte elismert legtisztább szabvány.",
      pl: "Każda oferowana przez nas sztabka i moneta to złoto próby 999,9 — 24 karaty, najczystszy standard uznawany na całym świecie.",
      ru: "Каждый предлагаемый нами слиток и каждая монета изготовлены из золота 999,9 пробы — 24 карата, самого высокого широко признанного стандарта чистоты.",
      nl: "Elke goudstaaf en munt die wij aanbieden bestaat uit 999,9 fijn goud — 24 karaat, de zuiverste wereldwijd erkende standaard.",
      da: "Hver guldbarre og mønt, vi tilbyder, består af 999,9 fint guld — 24 karat, den reneste globalt anerkendte standard.",
      fi: "Jokainen tarjoamamme harkko ja kolikko on 999,9-pitoista kultaa — 24 karaattia, maailmanlaajuisesti tunnustettu puhtain standardi.",
      sv: "Varje tacka och mynt vi erbjuder består av 999,9 fint guld — 24 karat, den renaste globalt erkända standarden.",
      fr: "Chaque lingot et chaque pièce que nous proposons est en or fin 999,9 — 24 carats, le standard de pureté le plus élevé reconnu dans le monde.",
      it: "Ogni lingotto e moneta che offriamo è in oro fino 999,9 — 24 carati, lo standard di purezza più elevato riconosciuto a livello internazionale.",
      es: "Cada lingote y moneda que ofrecemos es de oro fino 999,9 — 24 quilates, el estándar de pureza más alto reconocido internacionalmente.",
    },

    image: "/images/investment-gold/purity.png",
    imageWidth: 350,
    imageHeight: 233,
    imageAlt:
      "Five gold bars of increasing size, each stamped 999.9 purity",
  },

  {
    title: {
      de: "Gewicht & Stückelungen",
      en: "Weight & Denominations",
      tr: "Ağırlık ve Kupürler",
      sk: "Váha a nominály",
      cs: "Váha a nominály",
      hu: "Súly és címletek",
      pl: "Waga i nominały",
      ru: "Вес и номиналы",
      nl: "Gewicht & formaten",
      da: "Vægt & størrelser",
      fi: "Paino & kokoluokat",
      sv: "Vikt & storlekar",
      fr: "Poids & formats",
      it: "Peso & formati",
      es: "Peso & formatos",
    },

    description: {
      de: "Erhältlich von 1 Gramm bis zum vollen Kilobarren, sodass Sie klein anfangen oder in großem Maßstab investieren können — der Wert steigt direkt mit dem Gewicht.",
      en: "Available from 1 gram to a full kilo bar, so you can start small or invest at scale — value scales directly with weight.",
      tr: "1 gramdan tam kilo külçeye kadar mevcuttur, böylece küçük başlayabilir veya büyük ölçekte yatırım yapabilirsiniz — değer ağırlıkla doğrudan orantılıdır.",
      sk: "Dostupné od 1 gramu až po celú kilovú tehličku, takže môžete začať v malom alebo investovať vo veľkom — hodnota rastie priamo s váhou.",
      cs: "Dostupné od 1 gramu až po celou kilovou cihličku, takže můžete začít v malém nebo investovat ve velkém — hodnota roste přímo s váhou.",
      hu: "1 grammtól a teljes kilós rúdig elérhető, így akár kis léptékben kezdheti, akár nagyban fektethet be — az érték egyenesen arányos a súllyal.",
      pl: "Dostępne od 1 grama do pełnej sztabki kilogramowej, dzięki czemu możesz zacząć od małych ilości lub inwestować na większą skalę — wartość rośnie wprost proporcjonalnie do wagi.",
      ru: "Доступны варианты от 1 грамма до килограммового слитка, поэтому можно начать с небольшого веса или выбрать более крупный формат — стоимость напрямую зависит от веса.",
      nl: "Beschikbaar van 1 gram tot een volledige kilostaaf, zodat u klein kunt beginnen of op grotere schaal kunt kopen — de waarde neemt rechtstreeks toe met het gewicht.",
      da: "Fås fra 1 gram til en hel kilobarre, så du kan begynde i det små eller vælge større mængder — værdien følger vægten direkte.",
      fi: "Saatavilla 1 grammasta aina kokonaiseen kilon harkkoon, joten voit aloittaa pienestä tai valita suuremman koon — arvo kasvaa suoraan painon mukana.",
      sv: "Finns från 1 gram till en hel kilotacka, så du kan börja i liten skala eller välja större mängder — värdet följer vikten direkt.",
      fr: "Disponible de 1 gramme jusqu’au lingot d’un kilo, vous permettant de commencer modestement ou d’opter pour des formats plus importants — la valeur évolue directement avec le poids.",
      it: "Disponibile da 1 grammo fino al lingotto da un chilogrammo, così è possibile iniziare con piccoli formati o scegliere quantità maggiori — il valore cresce direttamente con il peso.",
      es: "Disponible desde 1 gramo hasta un lingote completo de un kilogramo, permitiéndole comenzar con cantidades pequeñas o elegir formatos mayores — el valor aumenta directamente con el peso.",
    },

    image: "/images/investment-gold/weight.png",
    imageWidth: 1536,
    imageHeight: 322,
    imageAlt:
      "A full range of gold bars from 1 gram to 1 kilogram, arranged by size",
  },
];

export const SECTION_2_POINTS: ValuePoint[] = [
  {
    title: {
      de: "Barren",
      en: "Bars",
      tr: "Külçeler",
      sk: "Tehličky",
      cs: "Cihličky",
      hu: "Rudak",
      pl: "Sztabki",
      ru: "Слитки",
      nl: "Goudstaven",
      da: "Guldbarer",
      fi: "Harkot",
      sv: "Tackor",
      fr: "Lingots",
      it: "Lingotti",
      es: "Lingotes",
    },

    description: {
      de: "Gegossene oder geprägte Barren von 1 g bis 1 kg, jeder mit Gewicht, Feingehalt und Prägestempel versehen.",
      en: "Cast or minted bars from 1g to 1kg, each stamped with its weight, purity and mint mark.",
      tr: "1 gramdan 1 kiloya kadar dökme veya darphane külçeleri — her biri ağırlığı, saflığı ve darphane damgasıyla işaretlenmiştir.",
      sk: "Liate alebo razené tehličky od 1 g do 1 kg, každá s vyrazenou váhou, rýdzosťou a značkou mincovne.",
      cs: "Lité nebo ražené cihličky od 1 g do 1 kg, každá s vyraženou váhou, ryzostí a značkou mincovny.",
      hu: "Öntött vagy vert rudak 1 g-tól 1 kg-ig, mindegyiken feltüntetve a súly, a finomság és a verde jelzése.",
      pl: "Sztabki lane lub bite od 1 g do 1 kg, każda z wybitą wagą, próbą i znakiem mennicy.",
      ru: "Литые или чеканные слитки весом от 1 г до 1 кг, каждый с указанием веса, пробы и клейма производителя.",
      nl: "Gegoten of geslagen goudstaven van 1 g tot 1 kg, elk voorzien van gewicht, zuiverheid en muntmerk.",
      da: "Støbte eller prægede guldbarer fra 1 g til 1 kg, alle mærket med vægt, renhed og producentens mærke.",
      fi: "Valettuja tai lyötyjä harkkoja 1 grammasta 1 kilogrammaan, jokaisessa merkittynä paino, pitoisuus ja valmistajan tunnus.",
      sv: "Gjutna eller präglade tackor från 1 g till 1 kg, var och en märkt med vikt, renhet och tillverkarens stämpel.",
      fr: "Lingots coulés ou frappés de 1 g à 1 kg, chacun portant son poids, son titre et la marque du fabricant.",
      it: "Lingotti colati o coniati da 1 g a 1 kg, ciascuno contrassegnato con peso, purezza e marchio del produttore.",
      es: "Lingotes fundidos o acuñados de 1 g a 1 kg, cada uno marcado con su peso, pureza y sello del fabricante.",
    },

    image: "/images/investment-gold/bars.png",
    imageWidth: 743,
    imageHeight: 234,
    imageAlt:
      "Gold bars of different weights, including 10oz, 20oz, 500g and 1 kilo",
  },

  {
    title: {
      de: "Münzen",
      en: "Coins",
      tr: "Sikkeler",
      sk: "Mince",
      cs: "Mince",
      hu: "Érmék",
      pl: "Monety",
      ru: "Монеты",
      nl: "Munten",
      da: "Mønter",
      fi: "Kolikot",
      sv: "Mynt",
      fr: "Pièces",
      it: "Monete",
      es: "Monedas",
    },

    description: {
      de: "Staatliche Münzen wie der Maple Leaf und der American Eagle — anerkannt, handelbar und überall auf der Welt leicht zu verifizieren.",
      en: "Sovereign coins such as the Maple Leaf and American Eagle — recognised, tradeable and easy to verify anywhere in the world.",
      tr: "Maple Leaf ve American Eagle gibi resmi sikkeler — dünyanın her yerinde tanınır, alınıp satılabilir ve kolayca doğrulanabilir.",
      sk: "Štátne mince ako Maple Leaf a American Eagle — uznávané, obchodovateľné a ľahko overiteľné kdekoľvek na svete.",
      cs: "Státní mince jako Maple Leaf a American Eagle — uznávané, obchodovatelné a snadno ověřitelné kdekoli na světě.",
      hu: "Állami érmék, mint a Maple Leaf és az American Eagle — elismertek, kereskedhetők és bárhol a világon könnyen ellenőrizhetők.",
      pl: "Oficjalne monety, takie jak Maple Leaf i American Eagle — uznawane, zbywalne i łatwe do zweryfikowania w każdym miejscu na świecie.",
      ru: "Инвестиционные монеты, такие как Maple Leaf и American Eagle, широко известны, обращаются на международных рынках и легко поддаются проверке.",
      nl: "Officiële beleggingsmunten zoals de Maple Leaf en American Eagle — internationaal erkend, verhandelbaar en eenvoudig te verifiëren.",
      da: "Officielle investeringsmønter som Maple Leaf og American Eagle — internationalt anerkendte, omsættelige og lette at verificere.",
      fi: "Viralliset sijoituskolikot, kuten Maple Leaf ja American Eagle — kansainvälisesti tunnettuja, vaihdettavia ja helposti todennettavia.",
      sv: "Officiella investeringsmynt som Maple Leaf och American Eagle — internationellt erkända, handelsbara och enkla att verifiera.",
      fr: "Des pièces d’investissement officielles telles que Maple Leaf et American Eagle — reconnues internationalement, négociables et faciles à vérifier.",
      it: "Monete da investimento ufficiali come Maple Leaf e American Eagle — riconosciute a livello internazionale, negoziabili e facili da verificare.",
      es: "Monedas de inversión oficiales como Maple Leaf y American Eagle — reconocidas internacionalmente, negociables y fáciles de verificar.",
    },

    image: "/images/investment-gold/coins.png",
    imageWidth: 773,
    imageHeight: 234,
    imageAlt:
      "Gold coins of increasing size, including Maple Leaf and American Eagle designs",
  },
];

export const SECTION_3_POINTS: ValuePoint[] = [
  {
    title: {
      de: "Zertifiziert & versiegelt",
      en: "Certified & Sealed",
      tr: "Sertifikalı ve Mühürlü",
      sk: "Certifikované a zapečatené",
      cs: "Certifikované a zapečetěné",
      hu: "Tanúsított és lezárt",
      pl: "Certyfikowane i zaplombowane",
      ru: "Сертифицировано и запечатано",
      nl: "Gecertificeerd & verzegeld",
      da: "Certificeret & forseglet",
      fi: "Sertifioitu & sinetöity",
      sv: "Certifierat & förseglat",
      fr: "Certifié & scellé",
      it: "Certificato & sigillato",
      es: "Certificado & sellado",
    },

    description: {
      de: "Kleinere Barren sind in manipulationssicheren Zertifikatskarten versiegelt, jede mit einer eindeutigen Seriennummer zur Überprüfung.",
      en: "Smaller bars are sealed in tamper-evident assay cards, each with a unique serial number for verification.",
      tr: "Daha küçük külçeler, doğrulama için benzersiz bir seri numarasına sahip, kurcalamaya karşı korumalı sertifika kartlarında mühürlenir.",
      sk: "Menšie tehličky sú zapečatené v neporušiteľných certifikačných kartách, každá s unikátnym sériovým číslom na overenie.",
      cs: "Menší cihličky jsou zapečetěné v neporušitelných certifikačních kartách, každá s unikátním sériovým číslem k ověření.",
      hu: "A kisebb rudakat manipulációbiztos tanúsítványkártyákba zárják, mindegyiken egyedi sorozatszámmal az ellenőrzéshez.",
      pl: "Mniejsze sztabki są zapieczętowane w odpornych na manipulacje kartach probierczych, każda z unikalnym numerem seryjnym umożliwiającym weryfikację.",
      ru: "Небольшие слитки запечатаны в защищённые от вскрытия сертификационные карты, каждая из которых имеет уникальный серийный номер для проверки.",
      nl: "Kleinere goudstaven zijn verzegeld in fraudebestendige certificaatkaarten, elk voorzien van een uniek serienummer voor verificatie.",
      da: "Mindre guldbarer er forseglet i manipulationssikre certifikatkort, hver med et unikt serienummer til verificering.",
      fi: "Pienemmät harkot on sinetöity peukaloinnilta suojattuihin sertifikaattikortteihin, joissa jokaisessa on yksilöllinen sarjanumero tarkistusta varten.",
      sv: "Mindre tackor är förseglade i manipulationssäkra certifikatkort, var och en med ett unikt serienummer för verifiering.",
      fr: "Les petits lingots sont scellés dans des cartes-certificats inviolables, chacune portant un numéro de série unique permettant leur vérification.",
      it: "I lingotti più piccoli sono sigillati in schede di certificazione antimanomissione, ciascuna dotata di un numero di serie univoco per la verifica.",
      es: "Los lingotes más pequeños están sellados en tarjetas de certificación a prueba de manipulaciones, cada una con un número de serie único para su verificación.",
    },

    image: "/images/investment-gold/certified.png",
    imageWidth: 758,
    imageHeight: 205,
    imageAlt:
      "Small gold bars sealed in tamper-evident assay cards, with raw gold nuggets",
  },

  {
    title: {
      de: "Sichere Präsentation",
      en: "Secure Presentation",
      tr: "Güvenli Sunum",
      sk: "Bezpečná prezentácia",
      cs: "Bezpečná prezentace",
      hu: "Biztonságos bemutatás",
      pl: "Bezpieczna prezentacja",
      ru: "Защитная упаковка",
      nl: "Veilige presentatie",
      da: "Sikker præsentation",
      fi: "Turvallinen pakkaus",
      sv: "Säker presentation",
      fr: "Présentation sécurisée",
      it: "Presentazione sicura",
      es: "Presentación segura",
    },

    description: {
      de: "Größere Barren sind zum Schutz und zur einfachen Aufbewahrung in Kassetten verpackt — bereit für einen Safe, ein Schließfach oder einen privaten Tresor.",
      en: "Larger bars are cased for protection and easy storage — ready for a safe, a deposit box, or a private vault.",
      tr: "Daha büyük külçeler koruma ve kolay saklama için kutulanır — bir kasa, emanet kutusu veya özel kasa için hazırdır.",
      sk: "Väčšie tehličky sú uložené v puzdrách pre ochranu a jednoduché skladovanie — pripravené do trezoru, bezpečnostnej schránky alebo súkromného sejfu.",
      cs: "Větší cihličky jsou uloženy v pouzdrech pro ochranu a snadné skladování — připravené do trezoru, bezpečnostní schránky nebo soukromého sejfu.",
      hu: "A nagyobb rudakat védelem és könnyű tárolás céljából dobozba helyezik — készen állva egy széfbe, letéti fiókba vagy magánpáncélterembe.",
      pl: "Większe sztabki są umieszczane w etui dla ochrony i łatwego przechowywania — gotowe do sejfu, skrytki depozytowej lub prywatnego skarbca.",
      ru: "Крупные слитки помещаются в защитные футляры для безопасного и удобного хранения — в сейфе, банковской ячейке или частном хранилище.",
      nl: "Grotere goudstaven worden in beschermende cassettes geleverd voor veilige en eenvoudige opslag — geschikt voor een kluis, bankkluis of privékluis.",
      da: "Større guldbarer leveres i beskyttende etuier for sikker og enkel opbevaring — klar til et pengeskab, en bankboks eller en privat boks.",
      fi: "Suuremmat harkot toimitetaan suojaavissa koteloissa turvallista ja helppoa säilytystä varten — valmiina kassakaappiin, tallelokeroon tai yksityiseen holviin.",
      sv: "Större tackor levereras i skyddande fodral för säker och enkel förvaring — redo för ett kassaskåp, bankfack eller privat valv.",
      fr: "Les lingots de plus grande taille sont présentés dans des coffrets protecteurs pour faciliter leur conservation — prêts à être placés dans un coffre-fort, un coffre bancaire ou une chambre forte privée.",
      it: "I lingotti più grandi sono custoditi in confezioni protettive per una conservazione semplice e sicura — pronti per una cassaforte, una cassetta di sicurezza o un caveau privato.",
      es: "Los lingotes de mayor tamaño se presentan en estuches protectores para facilitar su almacenamiento seguro — preparados para una caja fuerte, una caja de seguridad bancaria o una cámara acorazada privada.",
    },

    image: "/images/investment-gold/secure.png",
    imageWidth: 758,
    imageHeight: 205,
    imageAlt:
      "Larger gold bars presented in protective cases, from 10oz to 1 kilo",
  },
];

export const SECTION_4_POINTS: {
  title: LocalizedText;
  description: LocalizedText;
}[] = [
  {
    title: {
      de: "Wertspeicher",
      en: "Store of Value",
      tr: "Değer Saklama Aracı",
      sk: "Úschova hodnoty",
      cs: "Úschova hodnoty",
      hu: "Értékmegőrző",
      pl: "Lokata wartości",
      ru: "Сохранение стоимости",
      nl: "Waardeopslag",
      da: "Værdibeholdning",
      fi: "Arvon säilyttäjä",
      sv: "Värdebevarare",
      fr: "Réserve de valeur",
      it: "Riserva di valore",
      es: "Reserva de valor",
    },

    description: {
      de: "Gold hat seine Kaufkraft über Jahrhunderte, Währungen und Krisen hinweg bewahrt — ein Schutz gegen Inflation.",
      en: "Gold has held its purchasing power across centuries, currencies and crises — a hedge against inflation.",
      tr: "Altın, yüzyıllar, para birimleri ve krizler boyunca satın alma gücünü korumuştur — enflasyona karşı bir korunma aracıdır.",
      sk: "Zlato si udržalo svoju kúpnu silu naprieč storočiami, menami aj krízami — je ochranou proti inflácii.",
      cs: "Zlato si udrželo svou kupní sílu napříč staletími, měnami i krizemi — je ochranou proti inflaci.",
      hu: "Az arany évszázadokon, valutákon és válságokon át megőrizte vásárlóerejét — védelmet nyújt az infláció ellen.",
      pl: "Złoto zachowało swoją siłę nabywczą przez wieki, zmiany walut i kryzysy — stanowi zabezpieczenie przed inflacją.",
      ru: "Золото исторически сохраняло покупательную способность на протяжении веков, при смене валют и в периоды кризисов — поэтому его часто рассматривают как способ защиты от инфляции.",
      nl: "Goud heeft historisch zijn koopkracht behouden door eeuwen, valuta's en crises heen en wordt daarom vaak beschouwd als bescherming tegen inflatie.",
      da: "Guld har historisk bevaret sin købekraft gennem århundreder, valutaer og kriser og betragtes derfor ofte som en beskyttelse mod inflation.",
      fi: "Kulta on historiallisesti säilyttänyt ostovoimaansa vuosisatojen, valuuttojen ja kriisien läpi, minkä vuoksi sitä pidetään usein suojana inflaatiota vastaan.",
      sv: "Guld har historiskt bevarat sin köpkraft genom århundraden, valutor och kriser och betraktas därför ofta som ett skydd mot inflation.",
      fr: "L’or a historiquement conservé son pouvoir d’achat au fil des siècles, des monnaies et des crises, ce qui explique qu’il soit souvent considéré comme une protection contre l’inflation.",
      it: "Storicamente l’oro ha conservato il proprio potere d’acquisto attraverso secoli, valute e crisi, motivo per cui viene spesso considerato una protezione dall’inflazione.",
      es: "Históricamente, el oro ha conservado su poder adquisitivo a lo largo de siglos, monedas y crisis, por lo que suele considerarse una forma de protección frente a la inflación.",
    },
  },

  {
    title: {
      de: "Tragbar & liquide",
      en: "Portable & Liquid",
      tr: "Taşınabilir ve Likit",
      sk: "Prenosné a likvidné",
      cs: "Přenosné a likvidní",
      hu: "Hordozható és likvid",
      pl: "Przenośne i płynne",
      ru: "Компактность и ликвидность",
      nl: "Draagbaar & liquide",
      da: "Transportabelt & likvidt",
      fi: "Siirrettävä & likvidi",
      sv: "Portabelt & likvidt",
      fr: "Transportable & liquide",
      it: "Trasportabile & liquido",
      es: "Portátil & líquido",
    },

    description: {
      de: "Kompakt, leicht zu lagern und fast überall handelbar — eines der liquidesten physischen Vermögenswerte überhaupt.",
      en: "Compact, easy to store, and tradeable almost anywhere — one of the most liquid physical assets there is.",
      tr: "Kompakttır, saklaması kolaydır ve hemen her yerde alınıp satılabilir — var olan en likit fiziksel varlıklardan biridir.",
      sk: "Kompaktné, ľahko skladovateľné a obchodovateľné takmer kdekoľvek — jedno z najlikvidnejších fyzických aktív vôbec.",
      cs: "Kompaktní, snadno skladovatelné a obchodovatelné téměř kdekoli — jedno z nejlikvidnějších fyzických aktiv vůbec.",
      hu: "Kompakt, könnyen tárolható és szinte bárhol kereskedhető — az egyik legfolyékonyabb fizikai eszköz, amely létezik.",
      pl: "Kompaktowe, łatwe w przechowywaniu i zbywalne niemal wszędzie — jeden z najbardziej płynnych aktywów fizycznych.",
      ru: "Компактное, удобное для хранения и широко обращающееся на международных рынках золото относится к наиболее ликвидным физическим активам.",
      nl: "Compact, eenvoudig op te slaan en op veel markten verhandelbaar — goud behoort tot de meest liquide fysieke activa.",
      da: "Kompakt, let at opbevare og omsætteligt på mange markeder — guld hører til blandt de mest likvide fysiske aktiver.",
      fi: "Kompakti, helppo säilyttää ja laajalti vaihdettava — kulta kuuluu likvideimpiin fyysisiin omaisuuseriin.",
      sv: "Kompakt, enkelt att förvara och handelbart på många marknader — guld hör till de mest likvida fysiska tillgångarna.",
      fr: "Compact, facile à conserver et négociable sur de nombreux marchés — l’or figure parmi les actifs physiques les plus liquides.",
      it: "Compatto, facile da conservare e negoziabile su numerosi mercati — l’oro è tra gli asset fisici più liquidi.",
      es: "Compacto, fácil de almacenar y negociable en numerosos mercados — el oro se encuentra entre los activos físicos más líquidos.",
    },
  },

  {
    title: {
      de: "Weltweit anerkannt",
      en: "Globally Recognised",
      tr: "Küresel Olarak Tanınır",
      sk: "Celosvetovo uznávané",
      cs: "Celosvětově uznávané",
      hu: "Világszerte elismert",
      pl: "Uznawane na całym świecie",
      ru: "Признано во всём мире",
      nl: "Wereldwijd erkend",
      da: "Globalt anerkendt",
      fi: "Maailmanlaajuisesti tunnustettu",
      sv: "Globalt erkänt",
      fr: "Reconnu mondialement",
      it: "Riconosciuto a livello globale",
      es: "Reconocido mundialmente",
    },

    description: {
      de: "Auf jedem wichtigen Markt gleich akzeptiert und bewertet, mit Preisen, die durch einen transparenten globalen Spotpreis festgelegt werden.",
      en: "Accepted and valued the same way in every major market, with pricing set by a transparent global spot price.",
      tr: "Her büyük piyasada aynı şekilde kabul edilir ve değerlendirilir; fiyatlandırma şeffaf küresel spot fiyatla belirlenir.",
      sk: "Na každom väčšom trhu je akceptované a hodnotené rovnako, s cenou stanovenou podľa transparentnej globálnej spotovej ceny.",
      cs: "Na každém větším trhu je akceptované a hodnocené stejně, s cenou stanovenou podle transparentní globální spotové ceny.",
      hu: "Minden jelentős piacon ugyanúgy elfogadott és értékelt, az árát pedig egy átlátható globális azonnali (spot) ár határozza meg.",
      pl: "Akceptowane i wyceniane tak samo na każdym większym rynku, z ceną ustalaną na podstawie przejrzystej globalnej ceny spot.",
      ru: "Золото широко признаётся на крупнейших мировых рынках, а ориентиром для его стоимости служит прозрачная международная спотовая цена.",
      nl: "Goud wordt op de belangrijkste wereldmarkten algemeen erkend, waarbij de transparante internationale spotprijs als belangrijke prijsreferentie dient.",
      da: "Guld er bredt anerkendt på de største globale markeder, hvor den transparente internationale spotpris fungerer som en central prisreference.",
      fi: "Kulta tunnustetaan laajalti maailman tärkeimmillä markkinoilla, ja läpinäkyvä kansainvälinen spot-hinta toimii keskeisenä hintaviitteenä.",
      sv: "Guld är brett erkänt på världens största marknader, där det transparenta internationella spotpriset fungerar som en viktig prisreferens.",
      fr: "L’or est largement reconnu sur les principaux marchés mondiaux, le cours spot international transparent servant de référence essentielle pour sa valorisation.",
      it: "L’oro è ampiamente riconosciuto sui principali mercati mondiali, con il prezzo spot internazionale trasparente come importante riferimento di valore.",
      es: "El oro está ampliamente reconocido en los principales mercados mundiales, y el precio spot internacional transparente sirve como referencia fundamental para su valoración.",
    },
  },

  {
    title: {
      de: "Diversifikation",
      en: "Diversification",
      tr: "Çeşitlendirme",
      sk: "Diverzifikácia",
      cs: "Diverzifikace",
      hu: "Diverzifikáció",
      pl: "Dywersyfikacja",
      ru: "Диверсификация",
      nl: "Diversificatie",
      da: "Diversificering",
      fi: "Hajauttaminen",
      sv: "Diversifiering",
      fr: "Diversification",
      it: "Diversificazione",
      es: "Diversificación",
    },

    description: {
      de: "Ein greifbarer Vermögenswert, der sich unabhängig von Aktien und Anleihen bewegt — ein Ausgleich für ein breiteres Portfolio.",
      en: "A tangible asset that moves independently of stocks and bonds — balance for a wider portfolio.",
      tr: "Hisse senetleri ve tahvillerden bağımsız hareket eden somut bir varlık — daha geniş bir portföy için denge sağlar.",
      sk: "Hmatateľné aktívum, ktoré sa pohybuje nezávisle od akcií a dlhopisov — vyváženie pre širšie portfólio.",
      cs: "Hmatatelné aktivum, které se pohybuje nezávisle na akciích a dluhopisech — vyvážení pro širší portfolio.",
      hu: "Kézzelfogható eszköz, amely a részvényektől és kötvényektől függetlenül mozog — egyensúlyt teremt egy szélesebb portfólióban.",
      pl: "Namacalny aktyw, który porusza się niezależnie od akcji i obligacji — równowaga dla szerszego portfela inwestycyjnego.",
      ru: "Физический актив, динамика которого может отличаться от акций и облигаций, поэтому золото часто используется как один из элементов диверсифицированного портфеля.",
      nl: "Een tastbaar actief waarvan de koers zich anders kan gedragen dan aandelen en obligaties, waardoor goud vaak wordt gebruikt als onderdeel van een gediversifieerde portefeuille.",
      da: "Et fysisk aktiv, hvis prisudvikling kan adskille sig fra aktier og obligationer, hvilket gør guld til et almindeligt element i en diversificeret portefølje.",
      fi: "Fyysinen omaisuuserä, jonka hintakehitys voi poiketa osakkeista ja joukkovelkakirjoista, minkä vuoksi kultaa käytetään usein osana hajautettua salkkua.",
      sv: "En fysisk tillgång vars prisutveckling kan skilja sig från aktier och obligationer, vilket gör guld till ett vanligt inslag i en diversifierad portfölj.",
      fr: "Un actif tangible dont l’évolution peut différer de celle des actions et des obligations, ce qui explique pourquoi l’or est souvent intégré à un portefeuille diversifié.",
      it: "Un bene tangibile il cui andamento può differire da quello di azioni e obbligazioni, motivo per cui l’oro viene spesso utilizzato come componente di un portafoglio diversificato.",
      es: "Un activo tangible cuyo comportamiento puede diferir del de las acciones y los bonos, por lo que el oro suele formar parte de una cartera diversificada.",
    },
  },
];

export const SUMMARY_POINTS: LocalizedText[] = [
  {
    de: "999,9 Feingold, zertifiziert und überprüfbar",
    en: "999.9 fine gold, certified and verifiable",
    tr: "999.9 saf altın, sertifikalı ve doğrulanabilir",
    sk: "Rýdze zlato 999,9, certifikované a overiteľné",
    cs: "Ryzí zlato 999,9, certifikované a ověřitelné",
    hu: "999,9 finomságú arany, tanúsított és ellenőrizhető",
    pl: "Złoto próby 999,9, certyfikowane i weryfikowalne",
    ru: "Золото 999,9 пробы, сертифицированное и проверяемое",
    nl: "999,9 fijn goud, gecertificeerd en verifieerbaar",
    da: "999,9 fint guld, certificeret og verificerbart",
    fi: "999,9-pitoista kultaa, sertifioitu ja todennettavissa",
    sv: "999,9 fint guld, certifierat och verifierbart",
    fr: "Or fin 999,9, certifié et vérifiable",
    it: "Oro fino 999,9, certificato e verificabile",
    es: "Oro fino 999,9, certificado y verificable",
  },

  {
    de: "Von 1 Gramm bis zum vollen Kilo",
    en: "From 1 gram to a full kilo",
    tr: "1 gramdan tam kiloya kadar",
    sk: "Od 1 gramu až po celé kilo",
    cs: "Od 1 gramu až po celé kilo",
    hu: "1 gramtól a teljes kilóig",
    pl: "Od 1 grama do pełnego kilograma",
    ru: "От 1 грамма до полного килограмма",
    nl: "Van 1 gram tot een volledige kilo",
    da: "Fra 1 gram til et helt kilo",
    fi: "1 grammasta kokonaiseen kiloon",
    sv: "Från 1 gram till ett helt kilo",
    fr: "De 1 gramme jusqu’à un kilo complet",
    it: "Da 1 grammo fino a un chilogrammo completo",
    es: "Desde 1 gramo hasta un kilo completo",
  },

  {
    de: "Barren und staatliche Münzen von führenden Prägestätten",
    en: "Bars and sovereign coins, from leading mints",
    tr: "Önde gelen darphanelerden külçeler ve resmi sikkeler",
    sk: "Tehličky a štátne mince od popredných mincovní",
    cs: "Cihličky a státní mince od předních mincoven",
    hu: "Rudak és állami érmék a vezető pénzverdéktől",
    pl: "Sztabki i monety oficjalne z czołowych mennic",
    ru: "Слитки и инвестиционные монеты ведущих монетных дворов",
    nl: "Goudstaven en officiële munten van toonaangevende munthuizen",
    da: "Guldbarer og officielle mønter fra førende møntværker",
    fi: "Harkkoja ja virallisia sijoituskolikoita johtavilta rahapajoilta",
    sv: "Tackor och officiella investeringsmynt från ledande myntverk",
    fr: "Lingots et pièces d’investissement provenant de grandes monnaies",
    it: "Lingotti e monete da investimento delle principali zecche",
    es: "Lingotes y monedas de inversión de las principales casas de moneda",
  },

  {
    de: "Versiegelte, manipulationssichere Verpackung",
    en: "Sealed, tamper-evident packaging",
    tr: "Mühürlü, kurcalamaya karşı korumalı ambalaj",
    sk: "Zapečatené, neporušiteľné balenie",
    cs: "Zapečetěné, neporušitelné balení",
    hu: "Lezárt, manipulációbiztos csomagolás",
    pl: "Zaplombowane, odporne na manipulacje opakowanie",
    ru: "Запечатанная упаковка с защитой от вскрытия",
    nl: "Verzegelde, fraudebestendige verpakking",
    da: "Forseglet, manipulationssikker emballage",
    fi: "Sinetöity, peukaloinnilta suojattu pakkaus",
    sv: "Förseglad, manipulationssäker förpackning",
    fr: "Emballage scellé et inviolable",
    it: "Confezione sigillata e antimanomissione",
    es: "Embalaje sellado y a prueba de manipulaciones",
  },

  {
    de: "Ein greifbarer, weltweit liquider Wertspeicher",
    en: "A tangible, globally liquid store of value",
    tr: "Somut, küresel olarak likit bir değer saklama aracı",
    sk: "Hmatateľná úschova hodnoty, likvidná na celom svete",
    cs: "Hmatatelná úschova hodnoty, likvidní po celém světě",
    hu: "Kézzelfogható, globálisan likvid értékmegőrző",
    pl: "Namacalna, płynna na całym świecie lokata wartości",
    ru: "Материальный актив с высокой международной ликвидностью",
    nl: "Een tastbare waardeopslag met wereldwijde liquiditeit",
    da: "En fysisk værdibeholdning med global likviditet",
    fi: "Konkreettinen arvon säilyttäjä, jolla on maailmanlaajuista likviditeettiä",
    sv: "En fysisk värdebevarare med global likviditet",
    fr: "Une réserve de valeur tangible bénéficiant d’une liquidité mondiale",
    it: "Una riserva di valore tangibile con liquidità globale",
    es: "Una reserva de valor tangible con liquidez mundial",
  },
];