"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Product={id:string;name:string;slug:string;category:string;collection:string|null;description:string|null;price:number|null;currency:string;image_url:string|null;status:"draft"|"published";featured:boolean;sort_order:number};
type ProductForm={name:string;category:string;collection:string;description:string;price:string;currency:string;image_url:string;status:"draft"|"published";featured:boolean;sort_order:string};
const baseForm:ProductForm={name:"",category:"Jewellery",collection:"",description:"",price:"",currency:"EUR",image_url:"",status:"draft",featured:false,sort_order:"0"};

export default function AdminProductsPage(){
 const[authorized,setAuthorized]=useState(false),[products,setProducts]=useState<Product[]>([]),[form,setForm]=useState<ProductForm>(baseForm),[editingId,setEditingId]=useState<string|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[view,setView]=useState<"all"|"jewellery"|"watches">("all");
 useEffect(()=>{const p=new URLSearchParams(location.search).get("view");const next=p==="watches"?"watches":p==="jewellery"?"jewellery":"all";setView(next);if(next==="watches")setForm(v=>({...v,category:"Watches"}));fetch("/api/admin/auth/session",{cache:"no-store"}).then(r=>{if(!r.ok){location.href="/admin/login";return false;}return true;}).then(ok=>{if(ok){setAuthorized(true);void load();}});},[]);
 const filtered=useMemo(()=>products.filter(p=>{const isWatch=/watch/i.test(p.category)||/watch/i.test(p.collection||"");if(view==="watches"&&!isWatch)return false;if(view==="jewellery"&&isWatch)return false;const q=search.trim().toLowerCase();return !q||[p.name,p.category,p.collection||""].join(" ").toLowerCase().includes(q);}),[products,search,view]);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/products",{cache:"no-store"});if(r.status===401||r.status===403){location.href="/admin/login";return;}const d=await r.json();if(!r.ok)throw new Error(d.error||"Nepodarilo sa načítať produkty.");setProducts(d.products||[]);}catch(e){setMessage(e instanceof Error?e.message:"Chyba pri načítaní.");}finally{setLoading(false);}}
 function reset(){setEditingId(null);setForm({...baseForm,category:view==="watches"?"Watches":"Jewellery"});}
 function edit(p:Product){setEditingId(p.id);setForm({name:p.name,category:p.category,collection:p.collection||"",description:p.description||"",price:p.price==null?"":String(p.price),currency:p.currency,image_url:p.image_url||"",status:p.status,featured:p.featured,sort_order:String(p.sort_order||0)});scrollTo({top:0,behavior:"smooth"});}
 async function save(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const r=await fetch(editingId?`/api/admin/products/${editingId}`:"/api/admin/products",{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,price:form.price===""?null:Number(form.price),sort_order:Number(form.sort_order)||0})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Produkt sa nepodarilo uložiť.");setMessage(editingId?"Produkt bol upravený.":"Produkt bol vytvorený.");reset();await load();}catch(err){setMessage(err instanceof Error?err.message:"Chyba pri ukladaní.");}finally{setLoading(false);}}
 async function remove(id:string){if(!confirm("Naozaj chcete tento produkt odstrániť?"))return;const r=await fetch(`/api/admin/products/${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setMessage(d.error||"Produkt sa nepodarilo odstrániť.");return;}setProducts(v=>v.filter(p=>p.id!==id));setMessage("Produkt bol odstránený.");}
 if(!authorized)return <main className="flex min-h-screen items-center justify-center bg-[#120817] text-[#c8a96a]">Kontrolujem bezpečnú session…</main>;
 const heading=view==="watches"?"Hodinky":view==="jewellery"?"Šperky":"Produkty";
 return <main className="min-h-screen bg-[#120817] px-5 py-8 text-[#fffdf9] md:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 border-b border-[#c8a96a]/20 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[0.34em] text-[#c8a96a]">LIDYA Admin · Inventory</p><h1 className="mt-2 text-4xl md:text-5xl">{heading}</h1><p className="mt-2 text-sm text-white/45">Plná CRUD správa, publikovanie, ceny, kolekcie, obrázky, featured a poradie.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/products?view=jewellery" className="rounded-full border border-white/10 px-4 py-2 text-xs text-white/60">Šperky</Link><Link href="/admin/products?view=watches" className="rounded-full border border-white/10 px-4 py-2 text-xs text-white/60">Hodinky</Link><Link href="/admin" className="rounded-full border border-white/10 px-4 py-2 text-xs text-white/60">← Dashboard</Link></div></div>
 {message&&<div className="mt-5 rounded-xl border border-[#c8a96a]/20 bg-[#c8a96a]/5 px-4 py-3 text-sm text-[#e8d8b5]">{message}</div>}
 <div className="mt-6 grid gap-6 xl:grid-cols-[420px_1fr]"><section className="rounded-2xl border border-[#c8a96a]/15 bg-white/[0.035] p-5"><h2 className="text-2xl">{editingId?"Upraviť produkt":"Nový produkt"}</h2><form onSubmit={save} className="mt-5 space-y-3"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Názov produktu" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><div className="grid grid-cols-2 gap-3"><input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Kategória" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><input value={form.collection} onChange={e=>setForm({...form,collection:e.target.value})} placeholder="Kolekcia" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/></div><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Popis" rows={4} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><div className="grid grid-cols-[1fr_100px] gap-3"><input type="number" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Cena" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase().slice(0,3)})} placeholder="EUR" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/></div><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="URL obrázka z Media Library" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><div className="grid grid-cols-2 gap-3"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ProductForm["status"]})} className="rounded-xl border border-white/10 bg-[#1b0b20] px-4 py-3"><option value="draft">Koncept</option><option value="published">Publikované</option></select><input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})} placeholder="Poradie" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"/></div><label className="flex items-center gap-3 text-sm text-white/60"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Odporúčaný produkt</label><div className="flex gap-2"><button disabled={loading} className="flex-1 rounded-xl bg-[#c8a96a] px-4 py-3 font-semibold text-[#120817] disabled:opacity-50">{loading?"Ukladám…":editingId?"Uložiť zmeny":"Pridať produkt"}</button>{editingId&&<button type="button" onClick={reset} className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/55">Zrušiť</button>}</div></form></section>
 <section className="rounded-2xl border border-[#c8a96a]/15 bg-white/[0.035] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.24em] text-[#c8a96a]">Inventory</p><h2 className="mt-1 text-2xl">{heading}</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Hľadať…" className="rounded-full border border-white/10 bg-black/20 px-4 py-2 text-sm"/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-white/10 text-[10px] uppercase tracking-[0.16em] text-white/30"><tr><th className="pb-3">Produkt</th><th className="pb-3">Kategória</th><th className="pb-3">Cena</th><th className="pb-3">Stav</th><th className="pb-3 text-right">Akcie</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-b border-white/5 text-white/65"><td className="py-4"><div className="font-medium text-white/90">{p.name}</div><div className="mt-1 text-xs text-white/30">{p.collection||p.slug}</div></td><td>{p.category}</td><td>{p.price==null?"—":`${p.price.toLocaleString("sk-SK")} ${p.currency}`}</td><td>{p.status==="published"?"Publikované":"Koncept"}</td><td className="text-right"><button onClick={()=>edit(p)} className="mr-4 text-[#c8a96a]">Upraviť</button><button onClick={()=>void remove(p.id)} className="text-red-300/70">Zmazať</button></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<p className="py-10 text-center text-sm text-white/30">Žiadne položky.</p>}</div></section></div></div></main>;
}
