"use client";

import Image from "next/image";
import Link from "next/link";
import { useLanguage } from "@/components/LanguageProvider";
import { BOUTIQUES, COLLECTIONS, MATERIALS, localized } from "@/lib/content";
import type { Locale } from "@/lib/i18n";

type HomeCopy = {
  collectionsEyebrow: string; collectionsTitle: string; exploreCollections: string;
  materialsEyebrow: string; materialsTitle: string; materialsIntro: string; discoverMaterials: string;
  servicesEyebrow: string; servicesTitle: string; servicesIntro: string; bespoke: string; care: string; watch: string; exploreServices: string;
  aboutEyebrow: string; aboutTitle: string; aboutP1: string; aboutP2: string; discoverLidya: string;
  visitEyebrow: string; visitTitle: string; visitIntro: string; concierge: string; conciergeIntro: string;
  hotel: string; transfer: string; appointment: string; planVisit: string;
};

const COPY: Record<Locale, HomeCopy> = {
  en: { collectionsEyebrow:"The World of LIDYA",collectionsTitle:"Signature Collections",exploreCollections:"Explore all collections",materialsEyebrow:"The Materials of LIDYA",materialsTitle:"Chosen for beauty. Made to endure.",materialsIntro:"Precious materials selected for character, light and lasting value.",discoverMaterials:"Discover our materials",servicesEyebrow:"Bespoke & Care",servicesTitle:"Personal service, from first idea to lasting care.",servicesIntro:"From one-of-a-kind creations to jewellery and watch care, every detail is handled personally.",bespoke:"Bespoke",care:"Jewellery Care",watch:"Watch Service",exploreServices:"Explore services",aboutEyebrow:"Since 1989",aboutTitle:"Craftsmanship built on trust.",aboutP1:"For more than three decades, LIDYA has brought together handcraftsmanship, carefully selected materials and personal advice.",aboutP2:"Jewellery is personal. We believe choosing it should feel personal too.",discoverLidya:"Discover LIDYA",visitEyebrow:"Visit LIDYA",visitTitle:"Meet us in person.",visitIntro:"Discover LIDYA at Manavgat and selected Alba Hotels in Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"We can make your visit effortless from arrival to your private boutique appointment.",hotel:"Hotel",transfer:"Airport Transfer",appointment:"Private Appointment",planVisit:"Plan your visit" },
  de: { collectionsEyebrow:"Die Welt von LIDYA",collectionsTitle:"Signature-Kollektionen",exploreCollections:"Alle Kollektionen entdecken",materialsEyebrow:"Die Materialien von LIDYA",materialsTitle:"Für Schönheit gewählt. Für Dauer geschaffen.",materialsIntro:"Edle Materialien, ausgewählt nach Charakter, Licht und bleibendem Wert.",discoverMaterials:"Materialien entdecken",servicesEyebrow:"Maßanfertigung & Pflege",servicesTitle:"Persönlicher Service – von der ersten Idee bis zur dauerhaften Pflege.",servicesIntro:"Von Unikaten bis zur Schmuck- und Uhrenpflege wird jedes Detail persönlich betreut.",bespoke:"Maßanfertigung",care:"Schmuckpflege",watch:"Uhrenservice",exploreServices:"Services entdecken",aboutEyebrow:"Seit 1989",aboutTitle:"Handwerkskunst auf Vertrauen gebaut.",aboutP1:"Seit mehr als drei Jahrzehnten verbindet LIDYA Handwerkskunst, ausgewählte Materialien und persönliche Beratung.",aboutP2:"Schmuck ist persönlich. Auch die Auswahl sollte sich persönlich anfühlen.",discoverLidya:"LIDYA entdecken",visitEyebrow:"LIDYA besuchen",visitTitle:"Treffen Sie uns persönlich.",visitIntro:"Entdecken Sie LIDYA in Manavgat und in ausgewählten Alba Hotels in Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Wir gestalten Ihren Besuch von der Ankunft bis zum privaten Boutique-Termin mühelos.",hotel:"Hotel",transfer:"Flughafentransfer",appointment:"Privater Termin",planVisit:"Besuch planen" },
  tr: { collectionsEyebrow:"LIDYA Dünyası",collectionsTitle:"İmza Koleksiyonları",exploreCollections:"Tüm koleksiyonları keşfet",materialsEyebrow:"LIDYA Malzemeleri",materialsTitle:"Güzellik için seçildi. Kalıcılık için üretildi.",materialsIntro:"Karakteri, ışığı ve kalıcı değeri için seçilen değerli malzemeler.",discoverMaterials:"Malzemeleri keşfet",servicesEyebrow:"Özel Tasarım & Bakım",servicesTitle:"İlk fikirden uzun süreli bakıma kadar kişisel hizmet.",servicesIntro:"Özel üretimden mücevher ve saat bakımına kadar her ayrıntı kişisel olarak ele alınır.",bespoke:"Özel Tasarım",care:"Mücevher Bakımı",watch:"Saat Servisi",exploreServices:"Hizmetleri keşfet",aboutEyebrow:"1989'dan beri",aboutTitle:"Güven üzerine kurulu el işçiliği.",aboutP1:"LIDYA otuz yılı aşkın süredir el işçiliğini, özenle seçilmiş malzemeleri ve kişisel danışmanlığı bir araya getiriyor.",aboutP2:"Mücevher kişiseldir. Seçiminin de kişisel hissettirmesi gerektiğine inanıyoruz.",discoverLidya:"LIDYA'yı keşfet",visitEyebrow:"LIDYA'yı ziyaret edin",visitTitle:"Bizimle yüz yüze tanışın.",visitIntro:"LIDYA'yı Manavgat'ta ve Antalya'daki seçili Alba Otellerinde keşfedin.",concierge:"Özel Ziyaret Concierge",conciergeIntro:"Varışınızdan özel butik randevunuza kadar ziyaretinizi kolaylaştırabiliriz.",hotel:"Otel",transfer:"Havaalanı Transferi",appointment:"Özel Randevu",planVisit:"Ziyareti planla" },
  sk: { collectionsEyebrow:"Svet LIDYA",collectionsTitle:"Signature kolekcie",exploreCollections:"Objaviť všetky kolekcie",materialsEyebrow:"Materiály LIDYA",materialsTitle:"Vybrané pre krásu. Vytvorené, aby vydržali.",materialsIntro:"Vzácne materiály vyberané pre charakter, svetlo a trvalú hodnotu.",discoverMaterials:"Objaviť materiály",servicesEyebrow:"Na mieru & Starostlivosť",servicesTitle:"Osobný servis od prvého nápadu až po dlhodobú starostlivosť.",servicesIntro:"Od jedinečných šperkov na mieru až po servis šperkov a hodiniek je každý detail riešený osobne.",bespoke:"Na mieru",care:"Starostlivosť o šperky",watch:"Servis hodiniek",exploreServices:"Objaviť služby",aboutEyebrow:"Od roku 1989",aboutTitle:"Remeselnosť postavená na dôvere.",aboutP1:"LIDYA už viac než tri desaťročia spája ručnú remeselnú prácu, starostlivo vybrané materiály a osobné poradenstvo.",aboutP2:"Šperk je osobná záležitosť. Veríme, že osobný by mal byť aj jeho výber.",discoverLidya:"Objaviť LIDYA",visitEyebrow:"Navštívte LIDYA",visitTitle:"Spoznajte nás osobne.",visitIntro:"Objavte LIDYA v Manavgate a vo vybraných hoteloch Alba v Antalyi.",concierge:"Private Visit Concierge",conciergeIntro:"Vašu návštevu vieme zjednodušiť od príchodu až po súkromný termín v butiku.",hotel:"Hotel",transfer:"Transfer z letiska",appointment:"Súkromný termín",planVisit:"Naplánovať návštevu" },
  cs: { collectionsEyebrow:"Svět LIDYA",collectionsTitle:"Signature kolekce",exploreCollections:"Objevit všechny kolekce",materialsEyebrow:"Materiály LIDYA",materialsTitle:"Vybrané pro krásu. Vytvořené, aby vydržely.",materialsIntro:"Vzácné materiály vybrané pro charakter, světlo a trvalou hodnotu.",discoverMaterials:"Objevit materiály",servicesEyebrow:"Na míru & Péče",servicesTitle:"Osobní servis od prvního nápadu až po dlouhodobou péči.",servicesIntro:"Od jedinečných šperků na míru po servis šperků a hodinek řešíme každý detail osobně.",bespoke:"Na míru",care:"Péče o šperky",watch:"Servis hodinek",exploreServices:"Objevit služby",aboutEyebrow:"Od roku 1989",aboutTitle:"Řemeslnost postavená na důvěře.",aboutP1:"LIDYA už více než tři desetiletí spojuje ruční řemeslo, pečlivě vybrané materiály a osobní poradenství.",aboutP2:"Šperk je osobní. Věříme, že osobní by měl být i jeho výběr.",discoverLidya:"Objevit LIDYA",visitEyebrow:"Navštivte LIDYA",visitTitle:"Poznejte nás osobně.",visitIntro:"Objevte LIDYA v Manavgatu a ve vybraných hotelech Alba v Antalyi.",concierge:"Private Visit Concierge",conciergeIntro:"Vaši návštěvu usnadníme od příjezdu až po soukromý termín v butiku.",hotel:"Hotel",transfer:"Transfer z letiště",appointment:"Soukromý termín",planVisit:"Naplánovat návštěvu" },
  hu: { collectionsEyebrow:"A LIDYA világa",collectionsTitle:"Signature kollekciók",exploreCollections:"Összes kollekció",materialsEyebrow:"A LIDYA anyagai",materialsTitle:"A szépségért választva. Tartósságra alkotva.",materialsIntro:"Karakterük, fényük és maradandó értékük alapján választott nemes anyagok.",discoverMaterials:"Anyagok felfedezése",servicesEyebrow:"Egyedi & Gondoskodás",servicesTitle:"Személyes szolgáltatás az első ötlettől a tartós gondoskodásig.",servicesIntro:"Az egyedi alkotásoktól az ékszer- és óraszervizig minden részlet személyes figyelmet kap.",bespoke:"Egyedi készítés",care:"Ékszerápolás",watch:"Óraszerviz",exploreServices:"Szolgáltatások",aboutEyebrow:"1989 óta",aboutTitle:"Bizalomra épülő kézművesség.",aboutP1:"A LIDYA több mint három évtizede ötvözi a kézművességet, a gondosan választott anyagokat és a személyes tanácsadást.",aboutP2:"Az ékszer személyes. Szerintünk a választásának is annak kell lennie.",discoverLidya:"LIDYA felfedezése",visitEyebrow:"Látogassa meg a LIDYA-t",visitTitle:"Találkozzon velünk személyesen.",visitIntro:"Fedezze fel a LIDYA-t Manavgatban és Antalya válogatott Alba szállodáiban.",concierge:"Private Visit Concierge",conciergeIntro:"Érkezésétől a privát butikidőpontig megszervezzük látogatását.",hotel:"Hotel",transfer:"Reptéri transzfer",appointment:"Privát időpont",planVisit:"Látogatás tervezése" },
  pl: { collectionsEyebrow:"Świat LIDYA",collectionsTitle:"Kolekcje Signature",exploreCollections:"Poznaj wszystkie kolekcje",materialsEyebrow:"Materiały LIDYA",materialsTitle:"Wybrane dla piękna. Stworzone, by trwać.",materialsIntro:"Szlachetne materiały wybrane ze względu na charakter, światło i trwałą wartość.",discoverMaterials:"Poznaj materiały",servicesEyebrow:"Na zamówienie & Pielęgnacja",servicesTitle:"Osobista obsługa od pierwszego pomysłu po wieloletnią opiekę.",servicesIntro:"Od unikatowych projektów po pielęgnację biżuterii i zegarków – każdy detal traktujemy indywidualnie.",bespoke:"Na zamówienie",care:"Pielęgnacja biżuterii",watch:"Serwis zegarków",exploreServices:"Poznaj usługi",aboutEyebrow:"Od 1989",aboutTitle:"Rzemiosło zbudowane na zaufaniu.",aboutP1:"Od ponad trzech dekad LIDYA łączy rzemiosło, starannie wybrane materiały i osobiste doradztwo.",aboutP2:"Biżuteria jest osobista. Jej wybór również powinien taki być.",discoverLidya:"Poznaj LIDYA",visitEyebrow:"Odwiedź LIDYA",visitTitle:"Spotkaj się z nami osobiście.",visitIntro:"Odkryj LIDYA w Manavgat oraz w wybranych hotelach Alba w Antalyi.",concierge:"Private Visit Concierge",conciergeIntro:"Ułatwimy wizytę od przyjazdu aż po prywatne spotkanie w butiku.",hotel:"Hotel",transfer:"Transfer z lotniska",appointment:"Prywatne spotkanie",planVisit:"Zaplanuj wizytę" },
  ru: { collectionsEyebrow:"Мир LIDYA",collectionsTitle:"Знаковые коллекции",exploreCollections:"Все коллекции",materialsEyebrow:"Материалы LIDYA",materialsTitle:"Выбраны за красоту. Созданы надолго.",materialsIntro:"Драгоценные материалы, выбранные за характер, свет и непреходящую ценность.",discoverMaterials:"Открыть материалы",servicesEyebrow:"На заказ & Уход",servicesTitle:"Персональный сервис от первой идеи до долговременного ухода.",servicesIntro:"От уникальных изделий до ухода за украшениями и часами — каждая деталь решается лично.",bespoke:"На заказ",care:"Уход за украшениями",watch:"Сервис часов",exploreServices:"Услуги",aboutEyebrow:"С 1989 года",aboutTitle:"Мастерство, основанное на доверии.",aboutP1:"Более трех десятилетий LIDYA объединяет ручное мастерство, тщательно отобранные материалы и персональные консультации.",aboutP2:"Украшение — это личное. Его выбор тоже должен быть таким.",discoverLidya:"Открыть LIDYA",visitEyebrow:"Посетите LIDYA",visitTitle:"Познакомьтесь с нами лично.",visitIntro:"Откройте LIDYA в Манавгате и в избранных отелях Alba в Анталье.",concierge:"Private Visit Concierge",conciergeIntro:"Мы организуем ваш визит от прибытия до частной встречи в бутике.",hotel:"Отель",transfer:"Трансфер из аэропорта",appointment:"Частная встреча",planVisit:"Спланировать визит" },
  nl: { collectionsEyebrow:"De wereld van LIDYA",collectionsTitle:"Signature Collections",exploreCollections:"Alle collecties",materialsEyebrow:"De materialen van LIDYA",materialsTitle:"Gekozen om schoonheid. Gemaakt om te blijven.",materialsIntro:"Edele materialen geselecteerd op karakter, licht en blijvende waarde.",discoverMaterials:"Ontdek onze materialen",servicesEyebrow:"Maatwerk & Zorg",servicesTitle:"Persoonlijke service, van eerste idee tot blijvende zorg.",servicesIntro:"Van unieke creaties tot sieraden- en horlogezorg: elk detail krijgt persoonlijke aandacht.",bespoke:"Maatwerk",care:"Sieradenverzorging",watch:"Horlogeservice",exploreServices:"Ontdek services",aboutEyebrow:"Sinds 1989",aboutTitle:"Vakmanschap gebouwd op vertrouwen.",aboutP1:"Al meer dan drie decennia combineert LIDYA vakmanschap, zorgvuldig gekozen materialen en persoonlijk advies.",aboutP2:"Sieraden zijn persoonlijk. De keuze ervan hoort dat ook te zijn.",discoverLidya:"Ontdek LIDYA",visitEyebrow:"Bezoek LIDYA",visitTitle:"Ontmoet ons persoonlijk.",visitIntro:"Ontdek LIDYA in Manavgat en geselecteerde Alba Hotels in Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Wij maken uw bezoek moeiteloos, van aankomst tot privéafspraak in de boutique.",hotel:"Hotel",transfer:"Luchthaventransfer",appointment:"Privéafspraak",planVisit:"Plan uw bezoek" },
  da: { collectionsEyebrow:"LIDYAs verden",collectionsTitle:"Signature-kollektioner",exploreCollections:"Se alle kollektioner",materialsEyebrow:"LIDYAs materialer",materialsTitle:"Valgt for skønhed. Skabt til at vare.",materialsIntro:"Ædle materialer udvalgt for karakter, lys og varig værdi.",discoverMaterials:"Opdag materialerne",servicesEyebrow:"Skræddersyet & Pleje",servicesTitle:"Personlig service fra første idé til varig pleje.",servicesIntro:"Fra unikke kreationer til smykke- og urservice håndteres hver detalje personligt.",bespoke:"Skræddersyet",care:"Smykkepleje",watch:"Urservice",exploreServices:"Se services",aboutEyebrow:"Siden 1989",aboutTitle:"Håndværk bygget på tillid.",aboutP1:"I mere end tre årtier har LIDYA forenet håndværk, nøje udvalgte materialer og personlig rådgivning.",aboutP2:"Smykker er personlige. Det bør valget også være.",discoverLidya:"Opdag LIDYA",visitEyebrow:"Besøg LIDYA",visitTitle:"Mød os personligt.",visitIntro:"Oplev LIDYA i Manavgat og på udvalgte Alba Hotels i Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Vi gør besøget enkelt fra ankomst til privat boutique-aftale.",hotel:"Hotel",transfer:"Lufthavnstransfer",appointment:"Privat aftale",planVisit:"Planlæg besøg" },
  fi: { collectionsEyebrow:"LIDYAn maailma",collectionsTitle:"Signature-mallistot",exploreCollections:"Kaikki mallistot",materialsEyebrow:"LIDYAn materiaalit",materialsTitle:"Valittu kauneuden vuoksi. Tehty kestämään.",materialsIntro:"Arvokkaat materiaalit, jotka on valittu luonteen, valon ja pysyvän arvon perusteella.",discoverMaterials:"Tutustu materiaaleihin",servicesEyebrow:"Mittatilaus & Hoito",servicesTitle:"Henkilökohtaista palvelua ensimmäisestä ideasta pitkäaikaiseen hoitoon.",servicesIntro:"Ainutlaatuisista luomuksista koru- ja kellohuoltoon jokainen yksityiskohta hoidetaan henkilökohtaisesti.",bespoke:"Mittatilaus",care:"Korujen hoito",watch:"Kellohuolto",exploreServices:"Tutustu palveluihin",aboutEyebrow:"Vuodesta 1989",aboutTitle:"Luottamukseen perustuva käsityötaito.",aboutP1:"Yli kolmen vuosikymmenen ajan LIDYA on yhdistänyt käsityötaidon, huolella valitut materiaalit ja henkilökohtaisen neuvonnan.",aboutP2:"Koru on henkilökohtainen. Myös sen valinnan pitäisi tuntua siltä.",discoverLidya:"Tutustu LIDYAan",visitEyebrow:"Vieraile LIDYAssa",visitTitle:"Tapaa meidät henkilökohtaisesti.",visitIntro:"Tutustu LIDYAan Manavgatissa ja valituissa Alba Hotels -hotelleissa Antalyassa.",concierge:"Private Visit Concierge",conciergeIntro:"Teemme vierailustasi helpon saapumisesta yksityiseen boutique-tapaamiseen.",hotel:"Hotelli",transfer:"Lentokenttäkuljetus",appointment:"Yksityinen tapaaminen",planVisit:"Suunnittele vierailu" },
  sv: { collectionsEyebrow:"LIDYAs värld",collectionsTitle:"Signature Collections",exploreCollections:"Utforska alla kollektioner",materialsEyebrow:"LIDYAs material",materialsTitle:"Valda för skönhet. Skapade för att bestå.",materialsIntro:"Ädla material utvalda för karaktär, ljus och bestående värde.",discoverMaterials:"Upptäck materialen",servicesEyebrow:"Skräddarsytt & Omsorg",servicesTitle:"Personlig service från första idé till långvarig omsorg.",servicesIntro:"Från unika skapelser till smyckes- och klockservice hanteras varje detalj personligt.",bespoke:"Skräddarsytt",care:"Smyckesvård",watch:"Klockservice",exploreServices:"Utforska tjänster",aboutEyebrow:"Sedan 1989",aboutTitle:"Hantverk byggt på förtroende.",aboutP1:"I mer än tre decennier har LIDYA förenat hantverk, noggrant utvalda material och personlig rådgivning.",aboutP2:"Smycken är personliga. Valet bör också kännas personligt.",discoverLidya:"Upptäck LIDYA",visitEyebrow:"Besök LIDYA",visitTitle:"Möt oss personligen.",visitIntro:"Upptäck LIDYA i Manavgat och på utvalda Alba Hotels i Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Vi gör ditt besök enkelt från ankomst till privat boutique-tid.",hotel:"Hotell",transfer:"Flygplatstransfer",appointment:"Privat möte",planVisit:"Planera besök" },
  fr: { collectionsEyebrow:"L’univers LIDYA",collectionsTitle:"Collections Signature",exploreCollections:"Découvrir toutes les collections",materialsEyebrow:"Les matières LIDYA",materialsTitle:"Choisies pour leur beauté. Créées pour durer.",materialsIntro:"Des matières précieuses sélectionnées pour leur caractère, leur lumière et leur valeur durable.",discoverMaterials:"Découvrir les matières",servicesEyebrow:"Sur mesure & Entretien",servicesTitle:"Un service personnel, de la première idée à l’entretien durable.",servicesIntro:"De la création unique au soin des bijoux et des montres, chaque détail est traité personnellement.",bespoke:"Sur mesure",care:"Entretien des bijoux",watch:"Service horlogerie",exploreServices:"Découvrir les services",aboutEyebrow:"Depuis 1989",aboutTitle:"Un savoir-faire fondé sur la confiance.",aboutP1:"Depuis plus de trois décennies, LIDYA réunit savoir-faire artisanal, matières soigneusement sélectionnées et conseil personnel.",aboutP2:"Un bijou est personnel. Son choix doit l’être aussi.",discoverLidya:"Découvrir LIDYA",visitEyebrow:"Visiter LIDYA",visitTitle:"Rencontrez-nous en personne.",visitIntro:"Découvrez LIDYA à Manavgat et dans une sélection d’Alba Hotels à Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Nous simplifions votre visite, de votre arrivée à votre rendez-vous privé en boutique.",hotel:"Hôtel",transfer:"Transfert aéroport",appointment:"Rendez-vous privé",planVisit:"Planifier la visite" },
  it: { collectionsEyebrow:"Il mondo LIDYA",collectionsTitle:"Collezioni Signature",exploreCollections:"Scopri tutte le collezioni",materialsEyebrow:"I materiali LIDYA",materialsTitle:"Scelti per la bellezza. Creati per durare.",materialsIntro:"Materiali preziosi selezionati per carattere, luce e valore duraturo.",discoverMaterials:"Scopri i materiali",servicesEyebrow:"Su misura & Cura",servicesTitle:"Servizio personale, dalla prima idea alla cura nel tempo.",servicesIntro:"Dalle creazioni uniche alla cura di gioielli e orologi, ogni dettaglio viene seguito personalmente.",bespoke:"Su misura",care:"Cura dei gioielli",watch:"Servizio orologi",exploreServices:"Scopri i servizi",aboutEyebrow:"Dal 1989",aboutTitle:"Artigianalità fondata sulla fiducia.",aboutP1:"Da oltre tre decenni LIDYA unisce artigianalità, materiali selezionati con cura e consulenza personale.",aboutP2:"Un gioiello è personale. Anche la sua scelta dovrebbe esserlo.",discoverLidya:"Scopri LIDYA",visitEyebrow:"Visita LIDYA",visitTitle:"Incontraci di persona.",visitIntro:"Scopri LIDYA a Manavgat e in selezionati Alba Hotels ad Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Rendiamo la visita semplice dall’arrivo all’appuntamento privato in boutique.",hotel:"Hotel",transfer:"Transfer aeroporto",appointment:"Appuntamento privato",planVisit:"Pianifica la visita" },
  es: { collectionsEyebrow:"El mundo LIDYA",collectionsTitle:"Colecciones Signature",exploreCollections:"Explorar todas las colecciones",materialsEyebrow:"Los materiales LIDYA",materialsTitle:"Elegidos por su belleza. Creados para durar.",materialsIntro:"Materiales preciosos seleccionados por su carácter, luz y valor duradero.",discoverMaterials:"Descubrir materiales",servicesEyebrow:"A medida & Cuidado",servicesTitle:"Servicio personal, desde la primera idea hasta el cuidado duradero.",servicesIntro:"Desde piezas únicas hasta el cuidado de joyas y relojes, cada detalle se atiende personalmente.",bespoke:"A medida",care:"Cuidado de joyas",watch:"Servicio de relojes",exploreServices:"Explorar servicios",aboutEyebrow:"Desde 1989",aboutTitle:"Artesanía construida sobre la confianza.",aboutP1:"Durante más de tres décadas, LIDYA ha unido artesanía, materiales cuidadosamente seleccionados y asesoramiento personal.",aboutP2:"Una joya es personal. Elegirla también debería serlo.",discoverLidya:"Descubrir LIDYA",visitEyebrow:"Visita LIDYA",visitTitle:"Conócenos en persona.",visitIntro:"Descubre LIDYA en Manavgat y en una selección de Alba Hotels en Antalya.",concierge:"Private Visit Concierge",conciergeIntro:"Facilitamos tu visita desde la llegada hasta tu cita privada en boutique.",hotel:"Hotel",transfer:"Traslado aeropuerto",appointment:"Cita privada",planVisit:"Planificar visita" },
};

const collectionLinks: Record<string,string> = { pearls:"/pearls", wedding:"/wedding-rings", signature:"/signature-style", brilliants:"/brilliants" };
const boutiqueLinks: Record<string,string> = { manavgat:"/boutiques", resort:"https://www.albahotels.com.tr/en/resort-en/", royal:"https://www.albahotels.com.tr/en/royal-en/", queen:"https://www.albahotels.com.tr/en/queen-en/" };
const serviceImages = [
  { src: "/images/home-services/bespoke-jewellery.png", key: "bespoke" as const },
  { src: "/images/home-services/jewellery-care.png", key: "care" as const },
  { src: "/images/home-services/watch-service.png", key: "watch" as const },
];

function ArrowLink({href,label}:{href:string;label:string}) { return <Link href={href} className="inline-flex items-center gap-3 text-[0.62rem] font-semibold uppercase tracking-[0.22em] text-plum-dark transition-colors hover:text-gold"><span>{label}</span><span aria-hidden>→</span></Link>; }

export default function HomeLuxury() {
  const { locale } = useLanguage();
  const copy = COPY[locale];
  const featuredCollections = COLLECTIONS.slice(0,4);
  const featuredMaterials = ["yellowgold","diamond","gem","pearl"].map(id => MATERIALS.find(item=>item.id===id)).filter(Boolean) as typeof MATERIALS;

  return <>
    <section id="collections" className="bg-ivory py-20 md:py-28 lg:py-32"><div className="mx-auto max-w-[1440px] px-6 md:px-10 lg:px-16 xl:px-20"><div className="mb-12 flex flex-col gap-6 text-center lg:flex-row lg:items-end lg:justify-between lg:text-left"><div><span className="text-[0.66rem] font-semibold uppercase tracking-[0.32em] text-gold">{copy.collectionsEyebrow}</span><h2 className="mt-4 font-display text-5xl leading-none text-plum-dark md:text-6xl">{copy.collectionsTitle}</h2></div><ArrowLink href="/collections" label={copy.exploreCollections}/></div><div className="grid gap-4 md:grid-cols-2">{featuredCollections.map((item,index)=><Link key={item.id} href={collectionLinks[item.id]} className={`group relative overflow-hidden bg-plum-dark ${index<2?"min-h-[430px] lg:min-h-[500px]":"min-h-[360px] lg:min-h-[410px]"}`}><Image src={item.image} alt={localized(item.name,locale)} fill sizes="(min-width:768px) 50vw,100vw" className="object-cover transition-transform duration-[1200ms] group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-plum-dark/85 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 md:p-9"><h3 className="font-display text-3xl text-brand-white md:text-4xl">{localized(item.name,locale)}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-brand-white/65">{localized(item.description,locale)}</p></div></Link>)}</div><div className="mt-10 text-center"><ArrowLink href="/collections" label={copy.exploreCollections}/></div></div></section>

    <section className="bg-[#f2ede5] py-20 md:py-24"><div className="mx-auto max-w-[1440px] px-6 md:px-10 lg:px-16 xl:px-20"><div className="mx-auto mb-12 max-w-3xl text-center"><span className="text-[0.66rem] font-semibold uppercase tracking-[0.32em] text-gold">{copy.materialsEyebrow}</span><h2 className="mt-4 font-display text-4xl text-plum-dark md:text-5xl">{copy.materialsTitle}</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-grey md:text-base">{copy.materialsIntro}</p></div><div className="grid gap-px overflow-hidden border border-plum-dark/10 bg-plum-dark/10 sm:grid-cols-2 lg:grid-cols-4">{featuredMaterials.map(item=><div key={item.id} className="group bg-ivory p-8 text-center transition-colors hover:bg-white md:p-10"><span className="font-display text-5xl text-gold">{item.icon}</span><h3 className="mt-6 font-display text-2xl text-plum-dark">{localized(item.name,locale)}</h3><p className="mt-3 text-sm leading-6 text-grey">{localized(item.description,locale)}</p></div>)}</div><div className="mt-9 text-center"><ArrowLink href="/materials" label={copy.discoverMaterials}/></div></div></section>

    <section className="bg-ivory py-20 md:py-28"><div className="mx-auto max-w-[1440px] px-6 md:px-10 lg:px-16 xl:px-20"><div className="grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-5"><span className="text-[0.66rem] font-semibold uppercase tracking-[0.32em] text-gold">{copy.servicesEyebrow}</span><h2 className="mt-4 font-display text-4xl leading-tight text-plum-dark md:text-5xl">{copy.servicesTitle}</h2><p className="mt-5 text-sm leading-7 text-grey md:text-base">{copy.servicesIntro}</p><div className="mt-8"><ArrowLink href="/services" label={copy.exploreServices}/></div></div><div className="grid gap-4 sm:grid-cols-3 lg:col-span-7">{serviceImages.map(item=><div key={item.key} className="relative min-h-[260px] overflow-hidden bg-plum-dark md:min-h-[300px]"><Image src={item.src} alt={copy[item.key]} fill sizes="(min-width:1024px) 23vw,(min-width:640px) 33vw,100vw" className="object-cover" priority={false}/></div>)}</div></div></div></section>

    <section id="about" className="bg-plum-dark py-20 text-brand-white md:py-28"><div className="mx-auto grid max-w-[1440px] gap-10 px-6 md:px-10 lg:grid-cols-12 lg:items-center lg:px-16 xl:px-20"><div className="relative min-h-[430px] overflow-hidden lg:col-span-7 lg:min-h-[540px]"><Image src="/images/craftsmanship.jpg" alt="LIDYA craftsmanship" fill sizes="(min-width:1024px) 58vw,100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-plum-dark/35 to-transparent"/></div><div className="text-center lg:col-span-5 lg:text-left"><span className="text-[0.66rem] font-semibold uppercase tracking-[0.32em] text-gold">{copy.aboutEyebrow}</span><h2 className="mt-4 font-display text-5xl leading-tight text-[#F5EFE6]">{copy.aboutTitle}</h2><p className="mt-6 text-sm leading-7 text-brand-white/65 md:text-base">{copy.aboutP1}</p><p className="mt-4 text-sm leading-7 text-brand-white/65 md:text-base">{copy.aboutP2}</p><Link href="/about" className="mt-8 inline-flex items-center gap-3 text-[0.62rem] font-semibold uppercase tracking-[0.22em] text-gold hover:text-[#E8D8B5]">{copy.discoverLidya}<span>→</span></Link></div></div></section>

    <section id="boutiques" className="bg-ivory py-20 md:py-28"><div className="mx-auto max-w-[1440px] px-6 md:px-10 lg:px-16 xl:px-20"><div className="mx-auto mb-12 max-w-3xl text-center"><span className="text-[0.66rem] font-semibold uppercase tracking-[0.32em] text-gold">{copy.visitEyebrow}</span><h2 className="mt-4 font-display text-5xl text-plum-dark">{copy.visitTitle}</h2><p className="mt-5 text-sm leading-7 text-grey md:text-base">{copy.visitIntro}</p></div><div className="grid gap-3 md:grid-cols-4">{BOUTIQUES.map(item=>{const external=item.id!=="manavgat"; const href=boutiqueLinks[item.id]; return <a key={item.id} href={href} target={external?"_blank":undefined} rel={external?"noopener noreferrer":undefined} className="group relative min-h-[300px] overflow-hidden bg-plum-dark"><Image src={item.image} alt={item.name} fill sizes="(min-width:768px) 25vw,100vw" className="object-cover transition-transform duration-[1000ms] group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-plum-dark/90 via-plum-dark/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-center"><h3 className="font-display text-xl !text-brand-white">{item.name}</h3></div></a>})}</div><div
  className="mt-5 grid gap-5 border border-plum-dark/10 bg-cover bg-center p-7 md:grid-cols-[1.2fr_2fr_auto] md:items-center md:p-9"
  style={{ backgroundImage: 'url("/images/transfer/transfer.png")' }}
><div><span className="text-[0.62rem] font-semibold uppercase tracking-[0.26em] text-gold">{copy.concierge}</span><h3 className="mt-2 font-display text-3xl text-plum-dark">{copy.hotel} · {copy.transfer} · {copy.appointment}</h3></div><p className="text-sm leading-7 text-grey">{copy.conciergeIntro}</p><ArrowLink href="/private-visit" label={copy.planVisit}/></div></div></section>
  </>;
}
