"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Entry = { id:string; title:string; subtitle:string|null; metadata:Record<string,unknown>; status:string };

export default function AdminMediaPage() {
  const [entries,setEntries]=useState<Entry[]>([]); const [file,setFile]=useState<File|null>(null); const [alt,setAlt]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{ fetch("/api/admin/auth/session",{cache:"no-store"}).then(r=>{if(!r.ok){location.href="/admin/login";return;} void load();}); },[]);
  async function load(){ setLoading(true); try{ const r=await fetch("/api/admin/manage/media",{cache:"no-store"}); const d=await r.json(); if(!r.ok) throw new Error(d.error||"Load failed"); setEntries(d.entries||[]);}catch(e){setMessage(e instanceof Error?e.message:"Load failed");}finally{setLoading(false);} }
  async function upload(e:FormEvent){e.preventDefault(); if(!file)return; setLoading(true);setMessage(""); try{const data=new FormData();data.set("file",file);data.set("alt",alt);const r=await fetch("/api/admin/media/upload",{method:"POST",body:data});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed");setFile(null);setAlt("");setMessage("Súbor bol nahraný do LIDYA Media Library.");await load();}catch(err){setMessage(err instanceof Error?err.message:"Upload failed");}finally{setLoading(false);} }
  async function remove(id:string){if(!confirm("Odstrániť súbor z LIDYA Media Library?"))return;const r=await fetch(`/api/admin/media/${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setMessage(d.error||"Delete failed");return;}setEntries(v=>v.filter(x=>x.id!==id));setMessage("Súbor aj databázový záznam boli odstránené.");}
  return <main className="min-h-screen bg-[#120817] px-5 py-8 text-[#fffdf9] md:px-10"><div className="mx-auto max-w-7xl">
    <div className="flex items-end justify-between gap-4 border-b border-[#c8a96a]/20 pb-6"><div><p className="text-xs uppercase tracking-[0.34em] text-[#c8a96a]">Media management</p><h1 className="mt-2 text-4xl md:text-5xl">Médiá</h1><p className="mt-2 text-sm text-white/45">Reálna Supabase Storage knižnica pre obrázky, video a PDF. Max. 15 MB.</p></div><Link href="/admin" className="rounded-full border border-white/10 px-4 py-2 text-xs text-white/60">← Dashboard</Link></div>
    {message&&<div className="mt-5 rounded-xl border border-[#c8a96a]/20 bg-[#c8a96a]/5 px-4 py-3 text-sm text-[#e8d8b5]">{message}</div>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]"><section className="rounded-2xl border border-[#c8a96a]/15 bg-white/[0.035] p-5"><h2 className="text-2xl">Nahrať súbor</h2><form onSubmit={upload} className="mt-5 space-y-4"><input required type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,video/mp4,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="block w-full text-sm text-white/55 file:mr-3 file:rounded-lg file:border-0 file:bg-[#c8a96a] file:px-3 file:py-2 file:text-[#120817]"/><input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Alt text / popis" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><button disabled={loading||!file} className="w-full rounded-xl bg-[#c8a96a] px-4 py-3 font-semibold text-[#120817] disabled:opacity-50">{loading?"Pracujem…":"Nahrať do knižnice"}</button></form></section>
    <section className="rounded-2xl border border-[#c8a96a]/15 bg-white/[0.035] p-5"><div><p className="text-[10px] uppercase tracking-[0.24em] text-[#c8a96a]">Supabase Storage</p><h2 className="mt-1 text-2xl">Media Library</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{entries.map(entry=>{const url=String(entry.metadata?.meta1||"");const mime=String(entry.metadata?.mime||"");return <article key={entry.id} className="overflow-hidden rounded-xl border border-white/8 bg-black/15">{url&&mime.startsWith("image/")?<div className="relative aspect-video bg-black/30"><Image src={url} alt={entry.subtitle||entry.title} fill className="object-cover" sizes="320px" unoptimized/></div>:<div className="flex aspect-video items-center justify-center bg-black/30 text-xs uppercase tracking-[0.18em] text-[#c8a96a]">{mime||"FILE"}</div>}<div className="p-4"><p className="truncate text-sm text-white/85">{entry.title}</p><p className="mt-1 line-clamp-2 text-xs text-white/35">{entry.subtitle||"Bez alt textu"}</p><div className="mt-4 flex gap-3"><a href={url} target="_blank" rel="noreferrer" className="text-xs text-[#c8a96a]">Otvoriť ↗</a><button onClick={()=>void navigator.clipboard.writeText(url)} className="text-xs text-white/45">Kopírovať URL</button><button onClick={()=>void remove(entry.id)} className="ml-auto text-xs text-red-300/70">Zmazať</button></div></div></article>})}</div>{!loading&&!entries.length&&<p className="py-12 text-center text-sm text-white/30">Knižnica je zatiaľ prázdna.</p>}</section></div>
  </div></main>;
}
